# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ecpack

import flatbuffers

class T_EC_GETFREEWAITER_RS(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsT_EC_GETFREEWAITER_RS(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = T_EC_GETFREEWAITER_RS()
        x.Init(buf, n + offset)
        return x

    # T_EC_GETFREEWAITER_RS
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # T_EC_GETFREEWAITER_RS
    def SRsHead(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .S_RS_HEAD import S_RS_HEAD
            obj = S_RS_HEAD()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # T_EC_GETFREEWAITER_RS
    def BId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # T_EC_GETFREEWAITER_RS
    def WId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # T_EC_GETFREEWAITER_RS
    def SessionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # T_EC_GETFREEWAITER_RS
    def Promtpsmsg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

def T_EC_GETFREEWAITER_RSStart(builder): builder.StartObject(5)
def T_EC_GETFREEWAITER_RSAddSRsHead(builder, sRsHead): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sRsHead), 0)
def T_EC_GETFREEWAITER_RSAddBId(builder, bId): builder.PrependUint64Slot(1, bId, 0)
def T_EC_GETFREEWAITER_RSAddWId(builder, wId): builder.PrependUint64Slot(2, wId, 0)
def T_EC_GETFREEWAITER_RSAddSessionId(builder, sessionId): builder.PrependInt32Slot(3, sessionId, 0)
def T_EC_GETFREEWAITER_RSAddPromtpsmsg(builder, promtpsmsg): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(promtpsmsg), 0)
def T_EC_GETFREEWAITER_RSEnd(builder): return builder.EndObject()
