# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ecpack

import flatbuffers

class T_EC_GET_OFFLINE_CNT_RQ(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsT_EC_GET_OFFLINE_CNT_RQ(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = T_EC_GET_OFFLINE_CNT_RQ()
        x.Init(buf, n + offset)
        return x

    # T_EC_GET_OFFLINE_CNT_RQ
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # T_EC_GET_OFFLINE_CNT_RQ
    def SRqHead(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .S_RQ_HEAD import S_RQ_HEAD
            obj = S_RQ_HEAD()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # T_EC_GET_OFFLINE_CNT_RQ
    def BIdList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # T_EC_GET_OFFLINE_CNT_RQ
    def BIdListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def T_EC_GET_OFFLINE_CNT_RQStart(builder): builder.StartObject(2)
def T_EC_GET_OFFLINE_CNT_RQAddSRqHead(builder, sRqHead): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sRqHead), 0)
def T_EC_GET_OFFLINE_CNT_RQAddBIdList(builder, bIdList): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(bIdList), 0)
def T_EC_GET_OFFLINE_CNT_RQStartBIdListVector(builder, numElems): return builder.StartVector(8, numElems, 8)
def T_EC_GET_OFFLINE_CNT_RQEnd(builder): return builder.EndObject()
