# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ecpack

import flatbuffers

class T_EC_GETRECENTORDERS_RS(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsT_EC_GETRECENTORDERS_RS(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = T_EC_GETRECENTORDERS_RS()
        x.Init(buf, n + offset)
        return x

    # T_EC_GETRECENTORDERS_RS
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # T_EC_GETRECENTORDERS_RS
    def SRsHead(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .S_RS_HEAD import S_RS_HEAD
            obj = S_RS_HEAD()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # T_EC_GETRECENTORDERS_RS
    def Code(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # T_EC_GETRECENTORDERS_RS
    def OrderList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .T_ORDER_INFO import T_ORDER_INFO
            obj = T_ORDER_INFO()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # T_EC_GETRECENTORDERS_RS
    def OrderListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def T_EC_GETRECENTORDERS_RSStart(builder): builder.StartObject(3)
def T_EC_GETRECENTORDERS_RSAddSRsHead(builder, sRsHead): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sRsHead), 0)
def T_EC_GETRECENTORDERS_RSAddCode(builder, code): builder.PrependInt32Slot(1, code, 0)
def T_EC_GETRECENTORDERS_RSAddOrderList(builder, orderList): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(orderList), 0)
def T_EC_GETRECENTORDERS_RSStartOrderListVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def T_EC_GETRECENTORDERS_RSEnd(builder): return builder.EndObject()
