# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ecpack

import flatbuffers

class T_PROMPTMSG_INFO(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsT_PROMPTMSG_INFO(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = T_PROMPTMSG_INFO()
        x.Init(buf, n + offset)
        return x

    # T_PROMPTMSG_INFO
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # T_PROMPTMSG_INFO
    def BId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # T_PROMPTMSG_INFO
    def PromptsType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # T_PROMPTMSG_INFO
    def PromptsMsg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

def T_PROMPTMSG_INFOStart(builder): builder.StartObject(3)
def T_PROMPTMSG_INFOAddBId(builder, bId): builder.PrependUint64Slot(0, bId, 0)
def T_PROMPTMSG_INFOAddPromptsType(builder, promptsType): builder.PrependInt32Slot(1, promptsType, 0)
def T_PROMPTMSG_INFOAddPromptsMsg(builder, promptsMsg): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(promptsMsg), 0)
def T_PROMPTMSG_INFOEnd(builder): return builder.EndObject()
