// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var commonpack = commonpack || {};

/**
 * @const
 * @namespace
 */
var offcialpack = offcialpack || {};

/**
 * @constructor
 */
offcialpack.T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RS = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {offcialpack.T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RS}
 */
offcialpack.T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RS.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {offcialpack.T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RS=} obj
 * @returns {offcialpack.T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RS}
 */
offcialpack.T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RS.getRootAsT_CLIENT_OFFCIAL_GET_HISTORY_MSG_RS = function(bb, obj) {
  return (obj || new offcialpack.T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RS).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {commonpack.S_RS_HEAD=} obj
 * @returns {commonpack.S_RS_HEAD}
 */
offcialpack.T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RS.prototype.sRsHead = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new commonpack.S_RS_HEAD).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {number}
 */
offcialpack.T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RS.prototype.isFinish = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {offcialpack.T_OFFCIAL_MESSAGE=} obj
 * @returns {offcialpack.T_OFFCIAL_MESSAGE}
 */
offcialpack.T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RS.prototype.listSysMsgResponse = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new offcialpack.T_OFFCIAL_MESSAGE).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
offcialpack.T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RS.prototype.listSysMsgResponseLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
offcialpack.T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RS.startT_CLIENT_OFFCIAL_GET_HISTORY_MSG_RS = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sRsHeadOffset
 */
offcialpack.T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RS.addSRsHead = function(builder, sRsHeadOffset) {
  builder.addFieldStruct(0, sRsHeadOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} isFinish
 */
offcialpack.T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RS.addIsFinish = function(builder, isFinish) {
  builder.addFieldInt8(1, isFinish, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} listSysMsgResponseOffset
 */
offcialpack.T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RS.addListSysMsgResponse = function(builder, listSysMsgResponseOffset) {
  builder.addFieldOffset(2, listSysMsgResponseOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
offcialpack.T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RS.createListSysMsgResponseVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
offcialpack.T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RS.startListSysMsgResponseVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
offcialpack.T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RS.endT_CLIENT_OFFCIAL_GET_HISTORY_MSG_RS = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
offcialpack.T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RS.finishT_CLIENT_OFFCIAL_GET_HISTORY_MSG_RSBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.commonpack = commonpack;
this.offcialpack = offcialpack;
