// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var commonpack = commonpack || {};

/**
 * @const
 * @namespace
 */
var offcialpack = offcialpack || {};

/**
 * @constructor
 */
offcialpack.T_OFFCIAL_MESSAGE = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {offcialpack.T_OFFCIAL_MESSAGE}
 */
offcialpack.T_OFFCIAL_MESSAGE.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {offcialpack.T_OFFCIAL_MESSAGE=} obj
 * @returns {offcialpack.T_OFFCIAL_MESSAGE}
 */
offcialpack.T_OFFCIAL_MESSAGE.getRootAsT_OFFCIAL_MESSAGE = function(bb, obj) {
  return (obj || new offcialpack.T_OFFCIAL_MESSAGE).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
offcialpack.T_OFFCIAL_MESSAGE.prototype.messageId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
offcialpack.T_OFFCIAL_MESSAGE.prototype.offcialId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {commonpack.S_MSG=} obj
 * @returns {commonpack.S_MSG}
 */
offcialpack.T_OFFCIAL_MESSAGE.prototype.sMsg = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new commonpack.S_MSG).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
offcialpack.T_OFFCIAL_MESSAGE.prototype.bId = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
offcialpack.T_OFFCIAL_MESSAGE.prototype.wId = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
offcialpack.T_OFFCIAL_MESSAGE.prototype.cId = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
offcialpack.T_OFFCIAL_MESSAGE.startT_OFFCIAL_MESSAGE = function(builder) {
  builder.startObject(6);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} messageId
 */
offcialpack.T_OFFCIAL_MESSAGE.addMessageId = function(builder, messageId) {
  builder.addFieldInt64(0, messageId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} offcialId
 */
offcialpack.T_OFFCIAL_MESSAGE.addOffcialId = function(builder, offcialId) {
  builder.addFieldInt64(1, offcialId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sMsgOffset
 */
offcialpack.T_OFFCIAL_MESSAGE.addSMsg = function(builder, sMsgOffset) {
  builder.addFieldOffset(2, sMsgOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} bId
 */
offcialpack.T_OFFCIAL_MESSAGE.addBId = function(builder, bId) {
  builder.addFieldInt64(3, bId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} wId
 */
offcialpack.T_OFFCIAL_MESSAGE.addWId = function(builder, wId) {
  builder.addFieldInt64(4, wId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} cId
 */
offcialpack.T_OFFCIAL_MESSAGE.addCId = function(builder, cId) {
  builder.addFieldInt64(5, cId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
offcialpack.T_OFFCIAL_MESSAGE.endT_OFFCIAL_MESSAGE = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
offcialpack.T_OFFCIAL_MESSAGE.finishT_OFFCIAL_MESSAGEBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.commonpack = commonpack;
this.offcialpack = offcialpack;
