// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var commonpack = commonpack || {};

/**
 * @const
 * @namespace
 */
var offcialpack = offcialpack || {};

/**
 * @constructor
 */
offcialpack.T_OFFLINE_MESSAGE = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {offcialpack.T_OFFLINE_MESSAGE}
 */
offcialpack.T_OFFLINE_MESSAGE.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {offcialpack.T_OFFLINE_MESSAGE=} obj
 * @returns {offcialpack.T_OFFLINE_MESSAGE}
 */
offcialpack.T_OFFLINE_MESSAGE.getRootAsT_OFFLINE_MESSAGE = function(bb, obj) {
  return (obj || new offcialpack.T_OFFLINE_MESSAGE).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
offcialpack.T_OFFLINE_MESSAGE.prototype.messageId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {commonpack.S_MSG=} obj
 * @returns {commonpack.S_MSG}
 */
offcialpack.T_OFFLINE_MESSAGE.prototype.sMsg = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new commonpack.S_MSG).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
offcialpack.T_OFFLINE_MESSAGE.startT_OFFLINE_MESSAGE = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} messageId
 */
offcialpack.T_OFFLINE_MESSAGE.addMessageId = function(builder, messageId) {
  builder.addFieldInt64(0, messageId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sMsgOffset
 */
offcialpack.T_OFFLINE_MESSAGE.addSMsg = function(builder, sMsgOffset) {
  builder.addFieldOffset(1, sMsgOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
offcialpack.T_OFFLINE_MESSAGE.endT_OFFLINE_MESSAGE = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
offcialpack.T_OFFCIAL_OFFLINE_MESSAGE = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {offcialpack.T_OFFCIAL_OFFLINE_MESSAGE}
 */
offcialpack.T_OFFCIAL_OFFLINE_MESSAGE.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {offcialpack.T_OFFCIAL_OFFLINE_MESSAGE=} obj
 * @returns {offcialpack.T_OFFCIAL_OFFLINE_MESSAGE}
 */
offcialpack.T_OFFCIAL_OFFLINE_MESSAGE.getRootAsT_OFFCIAL_OFFLINE_MESSAGE = function(bb, obj) {
  return (obj || new offcialpack.T_OFFCIAL_OFFLINE_MESSAGE).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
offcialpack.T_OFFCIAL_OFFLINE_MESSAGE.prototype.isFinish = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @returns {flatbuffers.Long}
 */
offcialpack.T_OFFCIAL_OFFLINE_MESSAGE.prototype.offcialId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {number} index
 * @param {offcialpack.T_OFFLINE_MESSAGE=} obj
 * @returns {offcialpack.T_OFFLINE_MESSAGE}
 */
offcialpack.T_OFFCIAL_OFFLINE_MESSAGE.prototype.sMsg = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new offcialpack.T_OFFLINE_MESSAGE).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
offcialpack.T_OFFCIAL_OFFLINE_MESSAGE.prototype.sMsgLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {flatbuffers.Long}
 */
offcialpack.T_OFFCIAL_OFFLINE_MESSAGE.prototype.bId = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
offcialpack.T_OFFCIAL_OFFLINE_MESSAGE.prototype.wId = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
offcialpack.T_OFFCIAL_OFFLINE_MESSAGE.prototype.cId = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
offcialpack.T_OFFCIAL_OFFLINE_MESSAGE.startT_OFFCIAL_OFFLINE_MESSAGE = function(builder) {
  builder.startObject(6);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} isFinish
 */
offcialpack.T_OFFCIAL_OFFLINE_MESSAGE.addIsFinish = function(builder, isFinish) {
  builder.addFieldInt8(0, isFinish, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} offcialId
 */
offcialpack.T_OFFCIAL_OFFLINE_MESSAGE.addOffcialId = function(builder, offcialId) {
  builder.addFieldInt64(1, offcialId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sMsgOffset
 */
offcialpack.T_OFFCIAL_OFFLINE_MESSAGE.addSMsg = function(builder, sMsgOffset) {
  builder.addFieldOffset(2, sMsgOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
offcialpack.T_OFFCIAL_OFFLINE_MESSAGE.createSMsgVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
offcialpack.T_OFFCIAL_OFFLINE_MESSAGE.startSMsgVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} bId
 */
offcialpack.T_OFFCIAL_OFFLINE_MESSAGE.addBId = function(builder, bId) {
  builder.addFieldInt64(3, bId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} wId
 */
offcialpack.T_OFFCIAL_OFFLINE_MESSAGE.addWId = function(builder, wId) {
  builder.addFieldInt64(4, wId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} cId
 */
offcialpack.T_OFFCIAL_OFFLINE_MESSAGE.addCId = function(builder, cId) {
  builder.addFieldInt64(5, cId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
offcialpack.T_OFFCIAL_OFFLINE_MESSAGE.endT_OFFCIAL_OFFLINE_MESSAGE = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
offcialpack.T_OFFCIAL_OFFLINE_MESSAGE.finishT_OFFCIAL_OFFLINE_MESSAGEBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.commonpack = commonpack;
this.offcialpack = offcialpack;
