// automatically generated by the FlatBuffers compiler, do not modify

package scpack

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type T_GET_USER_STATUS_RS struct {
	_tab flatbuffers.Table
}

func GetRootAsT_GET_USER_STATUS_RS(buf []byte, offset flatbuffers.UOffsetT) *T_GET_USER_STATUS_RS {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &T_GET_USER_STATUS_RS{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *T_GET_USER_STATUS_RS) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *T_GET_USER_STATUS_RS) SRsHead(obj *S_RS_HEAD) *S_RS_HEAD {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(S_RS_HEAD)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *T_GET_USER_STATUS_RS) ListUserIds(j int) uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *T_GET_USER_STATUS_RS) ListUserIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func T_GET_USER_STATUS_RSStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func T_GET_USER_STATUS_RSAddSRsHead(builder *flatbuffers.Builder, sRsHead flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(sRsHead), 0)
}
func T_GET_USER_STATUS_RSAddListUserIds(builder *flatbuffers.Builder, listUserIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(listUserIds), 0)
}
func T_GET_USER_STATUS_RSStartListUserIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func T_GET_USER_STATUS_RSEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
