// automatically generated by the FlatBuffers compiler, do not modify

package scpack

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type T_SINGLE_CHAT_STATUS_RQ struct {
	_tab flatbuffers.Table
}

func GetRootAsT_SINGLE_CHAT_STATUS_RQ(buf []byte, offset flatbuffers.UOffsetT) *T_SINGLE_CHAT_STATUS_RQ {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &T_SINGLE_CHAT_STATUS_RQ{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *T_SINGLE_CHAT_STATUS_RQ) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *T_SINGLE_CHAT_STATUS_RQ) SRqHead(obj *S_RQ_HEAD) *S_RQ_HEAD {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(S_RQ_HEAD)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *T_SINGLE_CHAT_STATUS_RQ) OpUserId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *T_SINGLE_CHAT_STATUS_RQ) MutateOpUserId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *T_SINGLE_CHAT_STATUS_RQ) ChatStatus() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *T_SINGLE_CHAT_STATUS_RQ) MutateChatStatus(n int8) bool {
	return rcv._tab.MutateInt8Slot(8, n)
}

func T_SINGLE_CHAT_STATUS_RQStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func T_SINGLE_CHAT_STATUS_RQAddSRqHead(builder *flatbuffers.Builder, sRqHead flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(sRqHead), 0)
}
func T_SINGLE_CHAT_STATUS_RQAddOpUserId(builder *flatbuffers.Builder, opUserId uint64) {
	builder.PrependUint64Slot(1, opUserId, 0)
}
func T_SINGLE_CHAT_STATUS_RQAddChatStatus(builder *flatbuffers.Builder, chatStatus int8) {
	builder.PrependInt8Slot(2, chatStatus, 0)
}
func T_SINGLE_CHAT_STATUS_RQEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
