// automatically generated by the FlatBuffers compiler, do not modify

package scpack

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type T_SINGLE_CHAT_STATUS_RS struct {
	_tab flatbuffers.Table
}

func GetRootAsT_SINGLE_CHAT_STATUS_RS(buf []byte, offset flatbuffers.UOffsetT) *T_SINGLE_CHAT_STATUS_RS {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &T_SINGLE_CHAT_STATUS_RS{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *T_SINGLE_CHAT_STATUS_RS) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *T_SINGLE_CHAT_STATUS_RS) SRsHead(obj *S_RS_HEAD) *S_RS_HEAD {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(S_RS_HEAD)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *T_SINGLE_CHAT_STATUS_RS) OpUserId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *T_SINGLE_CHAT_STATUS_RS) MutateOpUserId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *T_SINGLE_CHAT_STATUS_RS) ChatStatus() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *T_SINGLE_CHAT_STATUS_RS) MutateChatStatus(n int8) bool {
	return rcv._tab.MutateInt8Slot(8, n)
}

func T_SINGLE_CHAT_STATUS_RSStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func T_SINGLE_CHAT_STATUS_RSAddSRsHead(builder *flatbuffers.Builder, sRsHead flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(sRsHead), 0)
}
func T_SINGLE_CHAT_STATUS_RSAddOpUserId(builder *flatbuffers.Builder, opUserId uint64) {
	builder.PrependUint64Slot(1, opUserId, 0)
}
func T_SINGLE_CHAT_STATUS_RSAddChatStatus(builder *flatbuffers.Builder, chatStatus int8) {
	builder.PrependInt8Slot(2, chatStatus, 0)
}
func T_SINGLE_CHAT_STATUS_RSEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
