// automatically generated by the FlatBuffers compiler, do not modify

package commonpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ACCOUNT_INFO extends Table {
  public static ACCOUNT_INFO getRootAsACCOUNT_INFO(ByteBuffer _bb) { return getRootAsACCOUNT_INFO(_bb, new ACCOUNT_INFO()); }
  public static ACCOUNT_INFO getRootAsACCOUNT_INFO(ByteBuffer _bb, ACCOUNT_INFO obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ACCOUNT_INFO __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long accountType() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long targetUserId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String targetUserToken() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer targetUserTokenAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public String targetUserName() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer targetUserNameAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }

  public static int createACCOUNT_INFO(FlatBufferBuilder builder,
      long account_type,
      long target_user_id,
      int target_user_tokenOffset,
      int target_user_nameOffset) {
    builder.startObject(4);
    ACCOUNT_INFO.addTargetUserId(builder, target_user_id);
    ACCOUNT_INFO.addAccountType(builder, account_type);
    ACCOUNT_INFO.addTargetUserName(builder, target_user_nameOffset);
    ACCOUNT_INFO.addTargetUserToken(builder, target_user_tokenOffset);
    return ACCOUNT_INFO.endACCOUNT_INFO(builder);
  }

  public static void startACCOUNT_INFO(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addAccountType(FlatBufferBuilder builder, long accountType) { builder.addLong(0, accountType, 0L); }
  public static void addTargetUserId(FlatBufferBuilder builder, long targetUserId) { builder.addLong(1, targetUserId, 0L); }
  public static void addTargetUserToken(FlatBufferBuilder builder, int targetUserTokenOffset) { builder.addOffset(2, targetUserTokenOffset, 0); }
  public static void addTargetUserName(FlatBufferBuilder builder, int targetUserNameOffset) { builder.addOffset(3, targetUserNameOffset, 0); }
  public static int endACCOUNT_INFO(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

