# automatically generated by the FlatBuffers compiler, do not modify

# namespace: offcialpack

import flatbuffers

class T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RQ(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsT_CLIENT_OFFCIAL_GET_HISTORY_MSG_RQ(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RQ()
        x.Init(buf, n + offset)
        return x

    # T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RQ
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RQ
    def SRqHead(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .S_RQ_HEAD import S_RQ_HEAD
            obj = S_RQ_HEAD()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RQ
    def MessageId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RQStart(builder): builder.StartObject(2)
def T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RQAddSRqHead(builder, sRqHead): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sRqHead), 0)
def T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RQAddMessageId(builder, messageId): builder.PrependUint64Slot(1, messageId, 0)
def T_CLIENT_OFFCIAL_GET_HISTORY_MSG_RQEnd(builder): return builder.EndObject()
