// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var commonpack = commonpack || {};

/**
 * @const
 * @namespace
 */
var scpack = scpack || {};

/**
 * @constructor
 */
scpack.T_CHAT_GET_OFFLINE_MESSAGE_RS = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {scpack.T_CHAT_GET_OFFLINE_MESSAGE_RS}
 */
scpack.T_CHAT_GET_OFFLINE_MESSAGE_RS.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {scpack.T_CHAT_GET_OFFLINE_MESSAGE_RS=} obj
 * @returns {scpack.T_CHAT_GET_OFFLINE_MESSAGE_RS}
 */
scpack.T_CHAT_GET_OFFLINE_MESSAGE_RS.getRootAsT_CHAT_GET_OFFLINE_MESSAGE_RS = function(bb, obj) {
  return (obj || new scpack.T_CHAT_GET_OFFLINE_MESSAGE_RS).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {commonpack.S_RS_HEAD=} obj
 * @returns {commonpack.S_RS_HEAD}
 */
scpack.T_CHAT_GET_OFFLINE_MESSAGE_RS.prototype.sRsHead = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new commonpack.S_RS_HEAD).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
scpack.T_CHAT_GET_OFFLINE_MESSAGE_RS.prototype.nextMessageId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {number} index
 * @param {scpack.T_OFFLINE_MSG=} obj
 * @returns {scpack.T_OFFLINE_MSG}
 */
scpack.T_CHAT_GET_OFFLINE_MESSAGE_RS.prototype.sOfflineMsgList = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new scpack.T_OFFLINE_MSG).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
scpack.T_CHAT_GET_OFFLINE_MESSAGE_RS.prototype.sOfflineMsgListLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
scpack.T_CHAT_GET_OFFLINE_MESSAGE_RS.startT_CHAT_GET_OFFLINE_MESSAGE_RS = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sRsHeadOffset
 */
scpack.T_CHAT_GET_OFFLINE_MESSAGE_RS.addSRsHead = function(builder, sRsHeadOffset) {
  builder.addFieldStruct(0, sRsHeadOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} nextMessageId
 */
scpack.T_CHAT_GET_OFFLINE_MESSAGE_RS.addNextMessageId = function(builder, nextMessageId) {
  builder.addFieldInt64(1, nextMessageId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sOfflineMsgListOffset
 */
scpack.T_CHAT_GET_OFFLINE_MESSAGE_RS.addSOfflineMsgList = function(builder, sOfflineMsgListOffset) {
  builder.addFieldOffset(2, sOfflineMsgListOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
scpack.T_CHAT_GET_OFFLINE_MESSAGE_RS.createSOfflineMsgListVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
scpack.T_CHAT_GET_OFFLINE_MESSAGE_RS.startSOfflineMsgListVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
scpack.T_CHAT_GET_OFFLINE_MESSAGE_RS.endT_CHAT_GET_OFFLINE_MESSAGE_RS = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
scpack.T_CHAT_GET_OFFLINE_MESSAGE_RS.finishT_CHAT_GET_OFFLINE_MESSAGE_RSBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.commonpack = commonpack;
this.scpack = scpack;
