// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var commonpack = commonpack || {};

/**
 * @const
 * @namespace
 */
var scpack = scpack || {};

/**
 * @constructor
 */
scpack.T_OFFLINE_MSG = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {scpack.T_OFFLINE_MSG}
 */
scpack.T_OFFLINE_MSG.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {scpack.T_OFFLINE_MSG=} obj
 * @returns {scpack.T_OFFLINE_MSG}
 */
scpack.T_OFFLINE_MSG.getRootAsT_OFFLINE_MSG = function(bb, obj) {
  return (obj || new scpack.T_OFFLINE_MSG).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
scpack.T_OFFLINE_MSG.prototype.opUserId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
scpack.T_OFFLINE_MSG.prototype.messageId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {commonpack.S_MSG=} obj
 * @returns {commonpack.S_MSG}
 */
scpack.T_OFFLINE_MSG.prototype.sMsg = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new commonpack.S_MSG).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
scpack.T_OFFLINE_MSG.prototype.bId = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
scpack.T_OFFLINE_MSG.prototype.wId = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
scpack.T_OFFLINE_MSG.prototype.cId = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
scpack.T_OFFLINE_MSG.startT_OFFLINE_MSG = function(builder) {
  builder.startObject(6);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} opUserId
 */
scpack.T_OFFLINE_MSG.addOpUserId = function(builder, opUserId) {
  builder.addFieldInt64(0, opUserId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} messageId
 */
scpack.T_OFFLINE_MSG.addMessageId = function(builder, messageId) {
  builder.addFieldInt64(1, messageId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sMsgOffset
 */
scpack.T_OFFLINE_MSG.addSMsg = function(builder, sMsgOffset) {
  builder.addFieldOffset(2, sMsgOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} bId
 */
scpack.T_OFFLINE_MSG.addBId = function(builder, bId) {
  builder.addFieldInt64(3, bId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} wId
 */
scpack.T_OFFLINE_MSG.addWId = function(builder, wId) {
  builder.addFieldInt64(4, wId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} cId
 */
scpack.T_OFFLINE_MSG.addCId = function(builder, cId) {
  builder.addFieldInt64(5, cId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
scpack.T_OFFLINE_MSG.endT_OFFLINE_MSG = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
scpack.T_OFFLINE_MSG.finishT_OFFLINE_MSGBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.commonpack = commonpack;
this.scpack = scpack;
