// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var commonpack = commonpack || {};

/**
 * @const
 * @namespace
 */
var scpack = scpack || {};

/**
 * @constructor
 */
scpack.T_SINGLE_CHAT_STATUS_RS = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {scpack.T_SINGLE_CHAT_STATUS_RS}
 */
scpack.T_SINGLE_CHAT_STATUS_RS.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {scpack.T_SINGLE_CHAT_STATUS_RS=} obj
 * @returns {scpack.T_SINGLE_CHAT_STATUS_RS}
 */
scpack.T_SINGLE_CHAT_STATUS_RS.getRootAsT_SINGLE_CHAT_STATUS_RS = function(bb, obj) {
  return (obj || new scpack.T_SINGLE_CHAT_STATUS_RS).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {commonpack.S_RS_HEAD=} obj
 * @returns {commonpack.S_RS_HEAD}
 */
scpack.T_SINGLE_CHAT_STATUS_RS.prototype.sRsHead = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new commonpack.S_RS_HEAD).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
scpack.T_SINGLE_CHAT_STATUS_RS.prototype.opUserId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
scpack.T_SINGLE_CHAT_STATUS_RS.prototype.chatStatus = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
scpack.T_SINGLE_CHAT_STATUS_RS.startT_SINGLE_CHAT_STATUS_RS = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sRsHeadOffset
 */
scpack.T_SINGLE_CHAT_STATUS_RS.addSRsHead = function(builder, sRsHeadOffset) {
  builder.addFieldStruct(0, sRsHeadOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} opUserId
 */
scpack.T_SINGLE_CHAT_STATUS_RS.addOpUserId = function(builder, opUserId) {
  builder.addFieldInt64(1, opUserId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} chatStatus
 */
scpack.T_SINGLE_CHAT_STATUS_RS.addChatStatus = function(builder, chatStatus) {
  builder.addFieldInt8(2, chatStatus, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
scpack.T_SINGLE_CHAT_STATUS_RS.endT_SINGLE_CHAT_STATUS_RS = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
scpack.T_SINGLE_CHAT_STATUS_RS.finishT_SINGLE_CHAT_STATUS_RSBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.commonpack = commonpack;
this.scpack = scpack;
