// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var commonpack = commonpack || {};

/**
 * @constructor
 */
commonpack.S_RQ_HEAD = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {commonpack.S_RQ_HEAD}
 */
commonpack.S_RQ_HEAD.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {flatbuffers.Long}
 */
commonpack.S_RQ_HEAD.prototype.userId = function() {
  return this.bb.readUint64(this.bb_pos);
};

/**
 * @returns {number}
 */
commonpack.S_RQ_HEAD.prototype.packSessionId = function() {
  return this.bb.readInt32(this.bb_pos + 8);
};

/**
 * @returns {number}
 */
commonpack.S_RQ_HEAD.prototype.platform = function() {
  return this.bb.readInt8(this.bb_pos + 12);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} user_id
 * @param {number} pack_session_id
 * @param {number} platform
 * @returns {flatbuffers.Offset}
 */
commonpack.S_RQ_HEAD.createS_RQ_HEAD = function(builder, user_id, pack_session_id, platform) {
  builder.prep(8, 16);
  builder.pad(3);
  builder.writeInt8(platform);
  builder.writeInt32(pack_session_id);
  builder.writeInt64(user_id);
  return builder.offset();
};

/**
 * @constructor
 */
commonpack.S_RS_HEAD = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {commonpack.S_RS_HEAD}
 */
commonpack.S_RS_HEAD.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {flatbuffers.Long}
 */
commonpack.S_RS_HEAD.prototype.userId = function() {
  return this.bb.readUint64(this.bb_pos);
};

/**
 * @returns {number}
 */
commonpack.S_RS_HEAD.prototype.packSessionId = function() {
  return this.bb.readInt32(this.bb_pos + 8);
};

/**
 * @returns {number}
 */
commonpack.S_RS_HEAD.prototype.result = function() {
  return this.bb.readInt32(this.bb_pos + 12);
};

/**
 * @returns {number}
 */
commonpack.S_RS_HEAD.prototype.platform = function() {
  return this.bb.readInt8(this.bb_pos + 16);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} user_id
 * @param {number} pack_session_id
 * @param {number} result
 * @param {number} platform
 * @returns {flatbuffers.Offset}
 */
commonpack.S_RS_HEAD.createS_RS_HEAD = function(builder, user_id, pack_session_id, result, platform) {
  builder.prep(8, 24);
  builder.pad(7);
  builder.writeInt8(platform);
  builder.writeInt32(result);
  builder.writeInt32(pack_session_id);
  builder.writeInt64(user_id);
  return builder.offset();
};

/**
 * @constructor
 */
commonpack.S_MSG = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {commonpack.S_MSG}
 */
commonpack.S_MSG.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {commonpack.S_MSG=} obj
 * @returns {commonpack.S_MSG}
 */
commonpack.S_MSG.getRootAsS_MSG = function(bb, obj) {
  return (obj || new commonpack.S_MSG).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
commonpack.S_MSG.prototype.appId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt16(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
commonpack.S_MSG.prototype.sessionId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
commonpack.S_MSG.prototype.chatType = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt16(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
commonpack.S_MSG.prototype.mType = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
commonpack.S_MSG.prototype.sType = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
commonpack.S_MSG.prototype.extType = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
commonpack.S_MSG.prototype.msgContent = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
commonpack.S_MSG.prototype.msgTime = function() {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
commonpack.S_MSG.prototype.sendUserName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
commonpack.S_MSG.startS_MSG = function(builder) {
  builder.startObject(9);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} appId
 */
commonpack.S_MSG.addAppId = function(builder, appId) {
  builder.addFieldInt16(0, appId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} sessionId
 */
commonpack.S_MSG.addSessionId = function(builder, sessionId) {
  builder.addFieldInt32(1, sessionId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} chatType
 */
commonpack.S_MSG.addChatType = function(builder, chatType) {
  builder.addFieldInt16(2, chatType, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} mType
 */
commonpack.S_MSG.addMType = function(builder, mType) {
  builder.addFieldInt32(3, mType, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} sType
 */
commonpack.S_MSG.addSType = function(builder, sType) {
  builder.addFieldInt32(4, sType, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} extType
 */
commonpack.S_MSG.addExtType = function(builder, extType) {
  builder.addFieldInt32(5, extType, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} msgContentOffset
 */
commonpack.S_MSG.addMsgContent = function(builder, msgContentOffset) {
  builder.addFieldOffset(6, msgContentOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} msgTime
 */
commonpack.S_MSG.addMsgTime = function(builder, msgTime) {
  builder.addFieldInt64(7, msgTime, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sendUserNameOffset
 */
commonpack.S_MSG.addSendUserName = function(builder, sendUserNameOffset) {
  builder.addFieldOffset(8, sendUserNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
commonpack.S_MSG.endS_MSG = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
commonpack.USER_BASE_INFO = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {commonpack.USER_BASE_INFO}
 */
commonpack.USER_BASE_INFO.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {commonpack.USER_BASE_INFO=} obj
 * @returns {commonpack.USER_BASE_INFO}
 */
commonpack.USER_BASE_INFO.getRootAsUSER_BASE_INFO = function(bb, obj) {
  return (obj || new commonpack.USER_BASE_INFO).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
commonpack.USER_BASE_INFO.prototype.userId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
commonpack.USER_BASE_INFO.prototype.userNickName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
commonpack.USER_BASE_INFO.prototype.userGroupIndex = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
commonpack.USER_BASE_INFO.startUSER_BASE_INFO = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} userId
 */
commonpack.USER_BASE_INFO.addUserId = function(builder, userId) {
  builder.addFieldInt64(0, userId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} userNickNameOffset
 */
commonpack.USER_BASE_INFO.addUserNickName = function(builder, userNickNameOffset) {
  builder.addFieldOffset(1, userNickNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} userGroupIndex
 */
commonpack.USER_BASE_INFO.addUserGroupIndex = function(builder, userGroupIndex) {
  builder.addFieldInt32(2, userGroupIndex, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
commonpack.USER_BASE_INFO.endUSER_BASE_INFO = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
commonpack.ACCOUNT_INFO = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {commonpack.ACCOUNT_INFO}
 */
commonpack.ACCOUNT_INFO.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {commonpack.ACCOUNT_INFO=} obj
 * @returns {commonpack.ACCOUNT_INFO}
 */
commonpack.ACCOUNT_INFO.getRootAsACCOUNT_INFO = function(bb, obj) {
  return (obj || new commonpack.ACCOUNT_INFO).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
commonpack.ACCOUNT_INFO.prototype.accountType = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
commonpack.ACCOUNT_INFO.prototype.targetUserId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
commonpack.ACCOUNT_INFO.prototype.targetUserToken = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
commonpack.ACCOUNT_INFO.prototype.targetUserName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
commonpack.ACCOUNT_INFO.startACCOUNT_INFO = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} accountType
 */
commonpack.ACCOUNT_INFO.addAccountType = function(builder, accountType) {
  builder.addFieldInt64(0, accountType, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} targetUserId
 */
commonpack.ACCOUNT_INFO.addTargetUserId = function(builder, targetUserId) {
  builder.addFieldInt64(1, targetUserId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} targetUserTokenOffset
 */
commonpack.ACCOUNT_INFO.addTargetUserToken = function(builder, targetUserTokenOffset) {
  builder.addFieldOffset(2, targetUserTokenOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} targetUserNameOffset
 */
commonpack.ACCOUNT_INFO.addTargetUserName = function(builder, targetUserNameOffset) {
  builder.addFieldOffset(3, targetUserNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
commonpack.ACCOUNT_INFO.endACCOUNT_INFO = function(builder) {
  var offset = builder.endObject();
  return offset;
};

// Exports for Node.js and RequireJS
this.commonpack = commonpack;
