// automatically generated by the FlatBuffers compiler, do not modify

package offcialpack

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RS struct {
	_tab flatbuffers.Table
}

func GetRootAsT_CLIENT_FANS_GET_OFFLINE_MESSAGE_RS(buf []byte, offset flatbuffers.UOffsetT) *T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RS {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RS{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RS) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RS) SRsHead(obj *S_RS_HEAD) *S_RS_HEAD {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(S_RS_HEAD)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RS) IsFinish() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RS) MutateIsFinish(n int8) bool {
	return rcv._tab.MutateInt8Slot(6, n)
}

func (rcv *T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RS) ListOffcialOfflineMsgResponse(obj *T_OFFCIAL_OFFLINE_MESSAGE, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RS) ListOffcialOfflineMsgResponseLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RS) ListPrivateMsgResponse(obj *T_OFFCIAL_MESSAGE, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RS) ListPrivateMsgResponseLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RSStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RSAddSRsHead(builder *flatbuffers.Builder, sRsHead flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(sRsHead), 0)
}
func T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RSAddIsFinish(builder *flatbuffers.Builder, isFinish int8) {
	builder.PrependInt8Slot(1, isFinish, 0)
}
func T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RSAddListOffcialOfflineMsgResponse(builder *flatbuffers.Builder, listOffcialOfflineMsgResponse flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(listOffcialOfflineMsgResponse), 0)
}
func T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RSStartListOffcialOfflineMsgResponseVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RSAddListPrivateMsgResponse(builder *flatbuffers.Builder, listPrivateMsgResponse flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(listPrivateMsgResponse), 0)
}
func T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RSStartListPrivateMsgResponseVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RSEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
