# automatically generated by the FlatBuffers compiler, do not modify

# namespace: scpack

import flatbuffers

class T_GET_MSG_UNREAD_RS(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsT_GET_MSG_UNREAD_RS(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = T_GET_MSG_UNREAD_RS()
        x.Init(buf, n + offset)
        return x

    # T_GET_MSG_UNREAD_RS
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # T_GET_MSG_UNREAD_RS
    def SRsHead(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .S_RS_HEAD import S_RS_HEAD
            obj = S_RS_HEAD()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # T_GET_MSG_UNREAD_RS
    def UnreadCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def T_GET_MSG_UNREAD_RSStart(builder): builder.StartObject(2)
def T_GET_MSG_UNREAD_RSAddSRsHead(builder, sRsHead): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sRsHead), 0)
def T_GET_MSG_UNREAD_RSAddUnreadCount(builder, unreadCount): builder.PrependInt32Slot(1, unreadCount, 0)
def T_GET_MSG_UNREAD_RSEnd(builder): return builder.EndObject()
