// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var commonpack = commonpack || {};

/**
 * @const
 * @namespace
 */
var grouppack = grouppack || {};

/**
 * @constructor
 */
grouppack.T_GROUP_CLIENT_SEND_MESSAGE_RQ = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {grouppack.T_GROUP_CLIENT_SEND_MESSAGE_RQ}
 */
grouppack.T_GROUP_CLIENT_SEND_MESSAGE_RQ.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {grouppack.T_GROUP_CLIENT_SEND_MESSAGE_RQ=} obj
 * @returns {grouppack.T_GROUP_CLIENT_SEND_MESSAGE_RQ}
 */
grouppack.T_GROUP_CLIENT_SEND_MESSAGE_RQ.getRootAsT_GROUP_CLIENT_SEND_MESSAGE_RQ = function(bb, obj) {
  return (obj || new grouppack.T_GROUP_CLIENT_SEND_MESSAGE_RQ).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {commonpack.S_RQ_HEAD=} obj
 * @returns {commonpack.S_RQ_HEAD}
 */
grouppack.T_GROUP_CLIENT_SEND_MESSAGE_RQ.prototype.sRqHead = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new commonpack.S_RQ_HEAD).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
grouppack.T_GROUP_CLIENT_SEND_MESSAGE_RQ.prototype.messageId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
grouppack.T_GROUP_CLIENT_SEND_MESSAGE_RQ.prototype.groupId = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {commonpack.S_MSG=} obj
 * @returns {commonpack.S_MSG}
 */
grouppack.T_GROUP_CLIENT_SEND_MESSAGE_RQ.prototype.sMsg = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new commonpack.S_MSG).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
grouppack.T_GROUP_CLIENT_SEND_MESSAGE_RQ.prototype.groupName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
grouppack.T_GROUP_CLIENT_SEND_MESSAGE_RQ.startT_GROUP_CLIENT_SEND_MESSAGE_RQ = function(builder) {
  builder.startObject(5);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sRqHeadOffset
 */
grouppack.T_GROUP_CLIENT_SEND_MESSAGE_RQ.addSRqHead = function(builder, sRqHeadOffset) {
  builder.addFieldStruct(0, sRqHeadOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} messageId
 */
grouppack.T_GROUP_CLIENT_SEND_MESSAGE_RQ.addMessageId = function(builder, messageId) {
  builder.addFieldInt64(1, messageId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} groupId
 */
grouppack.T_GROUP_CLIENT_SEND_MESSAGE_RQ.addGroupId = function(builder, groupId) {
  builder.addFieldInt64(2, groupId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sMsgOffset
 */
grouppack.T_GROUP_CLIENT_SEND_MESSAGE_RQ.addSMsg = function(builder, sMsgOffset) {
  builder.addFieldOffset(3, sMsgOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} groupNameOffset
 */
grouppack.T_GROUP_CLIENT_SEND_MESSAGE_RQ.addGroupName = function(builder, groupNameOffset) {
  builder.addFieldOffset(4, groupNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
grouppack.T_GROUP_CLIENT_SEND_MESSAGE_RQ.endT_GROUP_CLIENT_SEND_MESSAGE_RQ = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
grouppack.T_GROUP_CLIENT_SEND_MESSAGE_RQ.finishT_GROUP_CLIENT_SEND_MESSAGE_RQBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.commonpack = commonpack;
this.grouppack = grouppack;
