// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var commonpack = commonpack || {};

/**
 * @const
 * @namespace
 */
var grouppack = grouppack || {};

/**
 * @constructor
 */
grouppack.T_GROUP_DETAIL_INFO_RS = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {grouppack.T_GROUP_DETAIL_INFO_RS}
 */
grouppack.T_GROUP_DETAIL_INFO_RS.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {grouppack.T_GROUP_DETAIL_INFO_RS=} obj
 * @returns {grouppack.T_GROUP_DETAIL_INFO_RS}
 */
grouppack.T_GROUP_DETAIL_INFO_RS.getRootAsT_GROUP_DETAIL_INFO_RS = function(bb, obj) {
  return (obj || new grouppack.T_GROUP_DETAIL_INFO_RS).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {commonpack.S_RS_HEAD=} obj
 * @returns {commonpack.S_RS_HEAD}
 */
grouppack.T_GROUP_DETAIL_INFO_RS.prototype.sRsHead = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new commonpack.S_RS_HEAD).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {number} index
 * @param {commonpack.USER_BASE_INFO=} obj
 * @returns {commonpack.USER_BASE_INFO}
 */
grouppack.T_GROUP_DETAIL_INFO_RS.prototype.listMembersInfo = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new commonpack.USER_BASE_INFO).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
grouppack.T_GROUP_DETAIL_INFO_RS.prototype.listMembersInfoLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {flatbuffers.Long}
 */
grouppack.T_GROUP_DETAIL_INFO_RS.prototype.groupId = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
grouppack.T_GROUP_DETAIL_INFO_RS.prototype.groupMemberIndex = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
grouppack.T_GROUP_DETAIL_INFO_RS.startT_GROUP_DETAIL_INFO_RS = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sRsHeadOffset
 */
grouppack.T_GROUP_DETAIL_INFO_RS.addSRsHead = function(builder, sRsHeadOffset) {
  builder.addFieldStruct(0, sRsHeadOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} listMembersInfoOffset
 */
grouppack.T_GROUP_DETAIL_INFO_RS.addListMembersInfo = function(builder, listMembersInfoOffset) {
  builder.addFieldOffset(1, listMembersInfoOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
grouppack.T_GROUP_DETAIL_INFO_RS.createListMembersInfoVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
grouppack.T_GROUP_DETAIL_INFO_RS.startListMembersInfoVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} groupId
 */
grouppack.T_GROUP_DETAIL_INFO_RS.addGroupId = function(builder, groupId) {
  builder.addFieldInt64(2, groupId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} groupMemberIndex
 */
grouppack.T_GROUP_DETAIL_INFO_RS.addGroupMemberIndex = function(builder, groupMemberIndex) {
  builder.addFieldInt32(3, groupMemberIndex, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
grouppack.T_GROUP_DETAIL_INFO_RS.endT_GROUP_DETAIL_INFO_RS = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
grouppack.T_GROUP_DETAIL_INFO_RS.finishT_GROUP_DETAIL_INFO_RSBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.commonpack = commonpack;
this.grouppack = grouppack;
