// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var commonpack = commonpack || {};

/**
 * @const
 * @namespace
 */
var grouppack = grouppack || {};

/**
 * @constructor
 */
grouppack.T_OPERATE_GROUP_MSG = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {grouppack.T_OPERATE_GROUP_MSG}
 */
grouppack.T_OPERATE_GROUP_MSG.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {grouppack.T_OPERATE_GROUP_MSG=} obj
 * @returns {grouppack.T_OPERATE_GROUP_MSG}
 */
grouppack.T_OPERATE_GROUP_MSG.getRootAsT_OPERATE_GROUP_MSG = function(bb, obj) {
  return (obj || new grouppack.T_OPERATE_GROUP_MSG).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
grouppack.T_OPERATE_GROUP_MSG.prototype.msgTime = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
grouppack.T_OPERATE_GROUP_MSG.prototype.operateUserName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {number} index
 * @param {commonpack.USER_BASE_INFO=} obj
 * @returns {commonpack.USER_BASE_INFO}
 */
grouppack.T_OPERATE_GROUP_MSG.prototype.userInfoList = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new commonpack.USER_BASE_INFO).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
grouppack.T_OPERATE_GROUP_MSG.prototype.userInfoListLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
grouppack.T_OPERATE_GROUP_MSG.prototype.groupModifyContent = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
grouppack.T_OPERATE_GROUP_MSG.startT_OPERATE_GROUP_MSG = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} msgTime
 */
grouppack.T_OPERATE_GROUP_MSG.addMsgTime = function(builder, msgTime) {
  builder.addFieldInt64(0, msgTime, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} operateUserNameOffset
 */
grouppack.T_OPERATE_GROUP_MSG.addOperateUserName = function(builder, operateUserNameOffset) {
  builder.addFieldOffset(1, operateUserNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} userInfoListOffset
 */
grouppack.T_OPERATE_GROUP_MSG.addUserInfoList = function(builder, userInfoListOffset) {
  builder.addFieldOffset(2, userInfoListOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
grouppack.T_OPERATE_GROUP_MSG.createUserInfoListVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
grouppack.T_OPERATE_GROUP_MSG.startUserInfoListVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} groupModifyContentOffset
 */
grouppack.T_OPERATE_GROUP_MSG.addGroupModifyContent = function(builder, groupModifyContentOffset) {
  builder.addFieldOffset(3, groupModifyContentOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
grouppack.T_OPERATE_GROUP_MSG.endT_OPERATE_GROUP_MSG = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
grouppack.T_OFFLINE_GROUP_MSG = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {grouppack.T_OFFLINE_GROUP_MSG}
 */
grouppack.T_OFFLINE_GROUP_MSG.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {grouppack.T_OFFLINE_GROUP_MSG=} obj
 * @returns {grouppack.T_OFFLINE_GROUP_MSG}
 */
grouppack.T_OFFLINE_GROUP_MSG.getRootAsT_OFFLINE_GROUP_MSG = function(bb, obj) {
  return (obj || new grouppack.T_OFFLINE_GROUP_MSG).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
grouppack.T_OFFLINE_GROUP_MSG.prototype.userId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
grouppack.T_OFFLINE_GROUP_MSG.prototype.messageId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {commonpack.S_MSG=} obj
 * @returns {commonpack.S_MSG}
 */
grouppack.T_OFFLINE_GROUP_MSG.prototype.sMsg = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new commonpack.S_MSG).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {number}
 */
grouppack.T_OFFLINE_GROUP_MSG.prototype.bigMsgType = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {grouppack.T_OPERATE_GROUP_MSG=} obj
 * @returns {grouppack.T_OPERATE_GROUP_MSG}
 */
grouppack.T_OFFLINE_GROUP_MSG.prototype.operateGroupMsg = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? (obj || new grouppack.T_OPERATE_GROUP_MSG).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
grouppack.T_OFFLINE_GROUP_MSG.prototype.messageOldId = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {grouppack.T_GROUP_BASE_INFO=} obj
 * @returns {grouppack.T_GROUP_BASE_INFO}
 */
grouppack.T_OFFLINE_GROUP_MSG.prototype.groupInfo = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? (obj || new grouppack.T_GROUP_BASE_INFO).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
grouppack.T_OFFLINE_GROUP_MSG.startT_OFFLINE_GROUP_MSG = function(builder) {
  builder.startObject(7);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} userId
 */
grouppack.T_OFFLINE_GROUP_MSG.addUserId = function(builder, userId) {
  builder.addFieldInt64(0, userId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} messageId
 */
grouppack.T_OFFLINE_GROUP_MSG.addMessageId = function(builder, messageId) {
  builder.addFieldInt64(1, messageId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sMsgOffset
 */
grouppack.T_OFFLINE_GROUP_MSG.addSMsg = function(builder, sMsgOffset) {
  builder.addFieldOffset(2, sMsgOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} bigMsgType
 */
grouppack.T_OFFLINE_GROUP_MSG.addBigMsgType = function(builder, bigMsgType) {
  builder.addFieldInt32(3, bigMsgType, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} operateGroupMsgOffset
 */
grouppack.T_OFFLINE_GROUP_MSG.addOperateGroupMsg = function(builder, operateGroupMsgOffset) {
  builder.addFieldOffset(4, operateGroupMsgOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} messageOldId
 */
grouppack.T_OFFLINE_GROUP_MSG.addMessageOldId = function(builder, messageOldId) {
  builder.addFieldInt64(5, messageOldId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} groupInfoOffset
 */
grouppack.T_OFFLINE_GROUP_MSG.addGroupInfo = function(builder, groupInfoOffset) {
  builder.addFieldOffset(6, groupInfoOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
grouppack.T_OFFLINE_GROUP_MSG.endT_OFFLINE_GROUP_MSG = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
grouppack.T_OFFLINE_GROUP_MSG.finishT_OFFLINE_GROUP_MSGBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.commonpack = commonpack;
this.grouppack = grouppack;
