// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var commonpack = commonpack || {};

/**
 * @const
 * @namespace
 */
var grouppack = grouppack || {};

/**
 * @constructor
 */
grouppack.T_GET_BATCH_GROUP_INFO_RQ = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {grouppack.T_GET_BATCH_GROUP_INFO_RQ}
 */
grouppack.T_GET_BATCH_GROUP_INFO_RQ.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {grouppack.T_GET_BATCH_GROUP_INFO_RQ=} obj
 * @returns {grouppack.T_GET_BATCH_GROUP_INFO_RQ}
 */
grouppack.T_GET_BATCH_GROUP_INFO_RQ.getRootAsT_GET_BATCH_GROUP_INFO_RQ = function(bb, obj) {
  return (obj || new grouppack.T_GET_BATCH_GROUP_INFO_RQ).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {commonpack.S_RQ_HEAD=} obj
 * @returns {commonpack.S_RQ_HEAD}
 */
grouppack.T_GET_BATCH_GROUP_INFO_RQ.prototype.sRqHead = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new commonpack.S_RQ_HEAD).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {number} index
 * @returns {flatbuffers.Long}
 */
grouppack.T_GET_BATCH_GROUP_INFO_RQ.prototype.listGroupId = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint64(this.bb.__vector(this.bb_pos + offset) + index * 8) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
grouppack.T_GET_BATCH_GROUP_INFO_RQ.prototype.listGroupIdLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Uint64Array}
 */
grouppack.T_GET_BATCH_GROUP_INFO_RQ.prototype.listGroupIdArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? new Uint64Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
grouppack.T_GET_BATCH_GROUP_INFO_RQ.startT_GET_BATCH_GROUP_INFO_RQ = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sRqHeadOffset
 */
grouppack.T_GET_BATCH_GROUP_INFO_RQ.addSRqHead = function(builder, sRqHeadOffset) {
  builder.addFieldStruct(0, sRqHeadOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} listGroupIdOffset
 */
grouppack.T_GET_BATCH_GROUP_INFO_RQ.addListGroupId = function(builder, listGroupIdOffset) {
  builder.addFieldOffset(1, listGroupIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Long>} data
 * @returns {flatbuffers.Offset}
 */
grouppack.T_GET_BATCH_GROUP_INFO_RQ.createListGroupIdVector = function(builder, data) {
  builder.startVector(8, data.length, 8);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt64(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
grouppack.T_GET_BATCH_GROUP_INFO_RQ.startListGroupIdVector = function(builder, numElems) {
  builder.startVector(8, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
grouppack.T_GET_BATCH_GROUP_INFO_RQ.endT_GET_BATCH_GROUP_INFO_RQ = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
grouppack.T_GET_BATCH_GROUP_INFO_RQ.finishT_GET_BATCH_GROUP_INFO_RQBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.commonpack = commonpack;
this.grouppack = grouppack;
