// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var commonpack = commonpack || {};

/**
 * @const
 * @namespace
 */
var grouppack = grouppack || {};

/**
 * @constructor
 */
grouppack.T_GET_BATCH_GROUP_INFO_RS = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {grouppack.T_GET_BATCH_GROUP_INFO_RS}
 */
grouppack.T_GET_BATCH_GROUP_INFO_RS.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {grouppack.T_GET_BATCH_GROUP_INFO_RS=} obj
 * @returns {grouppack.T_GET_BATCH_GROUP_INFO_RS}
 */
grouppack.T_GET_BATCH_GROUP_INFO_RS.getRootAsT_GET_BATCH_GROUP_INFO_RS = function(bb, obj) {
  return (obj || new grouppack.T_GET_BATCH_GROUP_INFO_RS).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {commonpack.S_RS_HEAD=} obj
 * @returns {commonpack.S_RS_HEAD}
 */
grouppack.T_GET_BATCH_GROUP_INFO_RS.prototype.sRsHead = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new commonpack.S_RS_HEAD).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {number} index
 * @returns {flatbuffers.Long}
 */
grouppack.T_GET_BATCH_GROUP_INFO_RS.prototype.listGroupId = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint64(this.bb.__vector(this.bb_pos + offset) + index * 8) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
grouppack.T_GET_BATCH_GROUP_INFO_RS.prototype.listGroupIdLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Uint64Array}
 */
grouppack.T_GET_BATCH_GROUP_INFO_RS.prototype.listGroupIdArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? new Uint64Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {number} index
 * @param {grouppack.T_GROUP_BASE_INFO=} obj
 * @returns {grouppack.T_GROUP_BASE_INFO}
 */
grouppack.T_GET_BATCH_GROUP_INFO_RS.prototype.listGroupInfo = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new grouppack.T_GROUP_BASE_INFO).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
grouppack.T_GET_BATCH_GROUP_INFO_RS.prototype.listGroupInfoLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
grouppack.T_GET_BATCH_GROUP_INFO_RS.startT_GET_BATCH_GROUP_INFO_RS = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sRsHeadOffset
 */
grouppack.T_GET_BATCH_GROUP_INFO_RS.addSRsHead = function(builder, sRsHeadOffset) {
  builder.addFieldStruct(0, sRsHeadOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} listGroupIdOffset
 */
grouppack.T_GET_BATCH_GROUP_INFO_RS.addListGroupId = function(builder, listGroupIdOffset) {
  builder.addFieldOffset(1, listGroupIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Long>} data
 * @returns {flatbuffers.Offset}
 */
grouppack.T_GET_BATCH_GROUP_INFO_RS.createListGroupIdVector = function(builder, data) {
  builder.startVector(8, data.length, 8);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt64(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
grouppack.T_GET_BATCH_GROUP_INFO_RS.startListGroupIdVector = function(builder, numElems) {
  builder.startVector(8, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} listGroupInfoOffset
 */
grouppack.T_GET_BATCH_GROUP_INFO_RS.addListGroupInfo = function(builder, listGroupInfoOffset) {
  builder.addFieldOffset(2, listGroupInfoOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
grouppack.T_GET_BATCH_GROUP_INFO_RS.createListGroupInfoVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
grouppack.T_GET_BATCH_GROUP_INFO_RS.startListGroupInfoVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
grouppack.T_GET_BATCH_GROUP_INFO_RS.endT_GET_BATCH_GROUP_INFO_RS = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
grouppack.T_GET_BATCH_GROUP_INFO_RS.finishT_GET_BATCH_GROUP_INFO_RSBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.commonpack = commonpack;
this.grouppack = grouppack;
