// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var commonpack = commonpack || {};

/**
 * @const
 * @namespace
 */
var grouppack = grouppack || {};

/**
 * @constructor
 */
grouppack.T_GROUP_SAVE_CHANGE_RQ = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {grouppack.T_GROUP_SAVE_CHANGE_RQ}
 */
grouppack.T_GROUP_SAVE_CHANGE_RQ.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {grouppack.T_GROUP_SAVE_CHANGE_RQ=} obj
 * @returns {grouppack.T_GROUP_SAVE_CHANGE_RQ}
 */
grouppack.T_GROUP_SAVE_CHANGE_RQ.getRootAsT_GROUP_SAVE_CHANGE_RQ = function(bb, obj) {
  return (obj || new grouppack.T_GROUP_SAVE_CHANGE_RQ).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {commonpack.S_RQ_HEAD=} obj
 * @returns {commonpack.S_RQ_HEAD}
 */
grouppack.T_GROUP_SAVE_CHANGE_RQ.prototype.sRqHead = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new commonpack.S_RQ_HEAD).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
grouppack.T_GROUP_SAVE_CHANGE_RQ.prototype.groupId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
grouppack.T_GROUP_SAVE_CHANGE_RQ.prototype.saveType = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
grouppack.T_GROUP_SAVE_CHANGE_RQ.startT_GROUP_SAVE_CHANGE_RQ = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sRqHeadOffset
 */
grouppack.T_GROUP_SAVE_CHANGE_RQ.addSRqHead = function(builder, sRqHeadOffset) {
  builder.addFieldStruct(0, sRqHeadOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} groupId
 */
grouppack.T_GROUP_SAVE_CHANGE_RQ.addGroupId = function(builder, groupId) {
  builder.addFieldInt64(1, groupId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} saveType
 */
grouppack.T_GROUP_SAVE_CHANGE_RQ.addSaveType = function(builder, saveType) {
  builder.addFieldInt8(2, saveType, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
grouppack.T_GROUP_SAVE_CHANGE_RQ.endT_GROUP_SAVE_CHANGE_RQ = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
grouppack.T_GROUP_SAVE_CHANGE_RQ.finishT_GROUP_SAVE_CHANGE_RQBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.commonpack = commonpack;
this.grouppack = grouppack;
