// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var commonpack = commonpack || {};

/**
 * @const
 * @namespace
 */
var grouppack = grouppack || {};

/**
 * @constructor
 */
grouppack.T_GROUP_SCAN_RS = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {grouppack.T_GROUP_SCAN_RS}
 */
grouppack.T_GROUP_SCAN_RS.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {grouppack.T_GROUP_SCAN_RS=} obj
 * @returns {grouppack.T_GROUP_SCAN_RS}
 */
grouppack.T_GROUP_SCAN_RS.getRootAsT_GROUP_SCAN_RS = function(bb, obj) {
  return (obj || new grouppack.T_GROUP_SCAN_RS).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {commonpack.S_RS_HEAD=} obj
 * @returns {commonpack.S_RS_HEAD}
 */
grouppack.T_GROUP_SCAN_RS.prototype.sRsHead = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new commonpack.S_RS_HEAD).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
grouppack.T_GROUP_SCAN_RS.prototype.userIdShare = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {grouppack.T_GROUP_BASE_INFO=} obj
 * @returns {grouppack.T_GROUP_BASE_INFO}
 */
grouppack.T_GROUP_SCAN_RS.prototype.groupInfo = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new grouppack.T_GROUP_BASE_INFO).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {number}
 */
grouppack.T_GROUP_SCAN_RS.prototype.isMember = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
grouppack.T_GROUP_SCAN_RS.startT_GROUP_SCAN_RS = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sRsHeadOffset
 */
grouppack.T_GROUP_SCAN_RS.addSRsHead = function(builder, sRsHeadOffset) {
  builder.addFieldStruct(0, sRsHeadOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} userIdShare
 */
grouppack.T_GROUP_SCAN_RS.addUserIdShare = function(builder, userIdShare) {
  builder.addFieldInt64(1, userIdShare, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} groupInfoOffset
 */
grouppack.T_GROUP_SCAN_RS.addGroupInfo = function(builder, groupInfoOffset) {
  builder.addFieldOffset(2, groupInfoOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} isMember
 */
grouppack.T_GROUP_SCAN_RS.addIsMember = function(builder, isMember) {
  builder.addFieldInt32(3, isMember, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
grouppack.T_GROUP_SCAN_RS.endT_GROUP_SCAN_RS = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
grouppack.T_GROUP_SCAN_RS.finishT_GROUP_SCAN_RSBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.commonpack = commonpack;
this.grouppack = grouppack;
