# automatically generated by the FlatBuffers compiler, do not modify

# namespace: grouppack

import flatbuffers

class T_GET_BATCH_GROUP_INFO_RS(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsT_GET_BATCH_GROUP_INFO_RS(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = T_GET_BATCH_GROUP_INFO_RS()
        x.Init(buf, n + offset)
        return x

    # T_GET_BATCH_GROUP_INFO_RS
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # T_GET_BATCH_GROUP_INFO_RS
    def SRsHead(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .S_RS_HEAD import S_RS_HEAD
            obj = S_RS_HEAD()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # T_GET_BATCH_GROUP_INFO_RS
    def ListGroupId(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # T_GET_BATCH_GROUP_INFO_RS
    def ListGroupIdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # T_GET_BATCH_GROUP_INFO_RS
    def ListGroupInfo(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .T_GROUP_BASE_INFO import T_GROUP_BASE_INFO
            obj = T_GROUP_BASE_INFO()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # T_GET_BATCH_GROUP_INFO_RS
    def ListGroupInfoLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def T_GET_BATCH_GROUP_INFO_RSStart(builder): builder.StartObject(3)
def T_GET_BATCH_GROUP_INFO_RSAddSRsHead(builder, sRsHead): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sRsHead), 0)
def T_GET_BATCH_GROUP_INFO_RSAddListGroupId(builder, listGroupId): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(listGroupId), 0)
def T_GET_BATCH_GROUP_INFO_RSStartListGroupIdVector(builder, numElems): return builder.StartVector(8, numElems, 8)
def T_GET_BATCH_GROUP_INFO_RSAddListGroupInfo(builder, listGroupInfo): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(listGroupInfo), 0)
def T_GET_BATCH_GROUP_INFO_RSStartListGroupInfoVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def T_GET_BATCH_GROUP_INFO_RSEnd(builder): return builder.EndObject()
