# automatically generated by the FlatBuffers compiler, do not modify

# namespace: grouppack

import flatbuffers

class T_GROUP_DETAIL_INFO_RS(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsT_GROUP_DETAIL_INFO_RS(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = T_GROUP_DETAIL_INFO_RS()
        x.Init(buf, n + offset)
        return x

    # T_GROUP_DETAIL_INFO_RS
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # T_GROUP_DETAIL_INFO_RS
    def SRsHead(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .S_RS_HEAD import S_RS_HEAD
            obj = S_RS_HEAD()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # T_GROUP_DETAIL_INFO_RS
    def ListMembersInfo(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .USER_BASE_INFO import USER_BASE_INFO
            obj = USER_BASE_INFO()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # T_GROUP_DETAIL_INFO_RS
    def ListMembersInfoLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # T_GROUP_DETAIL_INFO_RS
    def GroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # T_GROUP_DETAIL_INFO_RS
    def GroupMemberIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def T_GROUP_DETAIL_INFO_RSStart(builder): builder.StartObject(4)
def T_GROUP_DETAIL_INFO_RSAddSRsHead(builder, sRsHead): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sRsHead), 0)
def T_GROUP_DETAIL_INFO_RSAddListMembersInfo(builder, listMembersInfo): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(listMembersInfo), 0)
def T_GROUP_DETAIL_INFO_RSStartListMembersInfoVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def T_GROUP_DETAIL_INFO_RSAddGroupId(builder, groupId): builder.PrependUint64Slot(2, groupId, 0)
def T_GROUP_DETAIL_INFO_RSAddGroupMemberIndex(builder, groupMemberIndex): builder.PrependInt32Slot(3, groupMemberIndex, 0)
def T_GROUP_DETAIL_INFO_RSEnd(builder): return builder.EndObject()
