# automatically generated by the FlatBuffers compiler, do not modify

# namespace: grouppack

import flatbuffers

class T_GROUP_MODIFY_ChANGE_RS(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsT_GROUP_MODIFY_ChANGE_RS(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = T_GROUP_MODIFY_ChANGE_RS()
        x.Init(buf, n + offset)
        return x

    # T_GROUP_MODIFY_ChANGE_RS
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # T_GROUP_MODIFY_ChANGE_RS
    def SRsHead(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .S_RS_HEAD import S_RS_HEAD
            obj = S_RS_HEAD()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # T_GROUP_MODIFY_ChANGE_RS
    def GroupInfo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .T_GROUP_BASE_INFO import T_GROUP_BASE_INFO
            obj = T_GROUP_BASE_INFO()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # T_GROUP_MODIFY_ChANGE_RS
    def OfflineGroupMsg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .T_OFFLINE_GROUP_MSG import T_OFFLINE_GROUP_MSG
            obj = T_OFFLINE_GROUP_MSG()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def T_GROUP_MODIFY_ChANGE_RSStart(builder): builder.StartObject(3)
def T_GROUP_MODIFY_ChANGE_RSAddSRsHead(builder, sRsHead): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sRsHead), 0)
def T_GROUP_MODIFY_ChANGE_RSAddGroupInfo(builder, groupInfo): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(groupInfo), 0)
def T_GROUP_MODIFY_ChANGE_RSAddOfflineGroupMsg(builder, offlineGroupMsg): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(offlineGroupMsg), 0)
def T_GROUP_MODIFY_ChANGE_RSEnd(builder): return builder.EndObject()
