# automatically generated by the FlatBuffers compiler, do not modify

# namespace: grouppack

import flatbuffers

class T_GROUP_CLIENT_SEND_MESSAGE_RS(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsT_GROUP_CLIENT_SEND_MESSAGE_RS(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = T_GROUP_CLIENT_SEND_MESSAGE_RS()
        x.Init(buf, n + offset)
        return x

    # T_GROUP_CLIENT_SEND_MESSAGE_RS
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # T_GROUP_CLIENT_SEND_MESSAGE_RS
    def SRsHead(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .S_RS_HEAD import S_RS_HEAD
            obj = S_RS_HEAD()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # T_GROUP_CLIENT_SEND_MESSAGE_RS
    def MessageId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # T_GROUP_CLIENT_SEND_MESSAGE_RS
    def GroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # T_GROUP_CLIENT_SEND_MESSAGE_RS
    def SMsg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .S_MSG import S_MSG
            obj = S_MSG()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def T_GROUP_CLIENT_SEND_MESSAGE_RSStart(builder): builder.StartObject(4)
def T_GROUP_CLIENT_SEND_MESSAGE_RSAddSRsHead(builder, sRsHead): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sRsHead), 0)
def T_GROUP_CLIENT_SEND_MESSAGE_RSAddMessageId(builder, messageId): builder.PrependUint64Slot(1, messageId, 0)
def T_GROUP_CLIENT_SEND_MESSAGE_RSAddGroupId(builder, groupId): builder.PrependUint64Slot(2, groupId, 0)
def T_GROUP_CLIENT_SEND_MESSAGE_RSAddSMsg(builder, sMsg): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(sMsg), 0)
def T_GROUP_CLIENT_SEND_MESSAGE_RSEnd(builder): return builder.EndObject()
