# automatically generated by the FlatBuffers compiler, do not modify

# namespace: userpack

import flatbuffers

class T_GET_USERINFO(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsT_GET_USERINFO(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = T_GET_USERINFO()
        x.Init(buf, n + offset)
        return x

    # T_GET_USERINFO
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # T_GET_USERINFO
    def UserId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # T_GET_USERINFO
    def UserName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # T_GET_USERINFO
    def NickName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # T_GET_USERINFO
    def Mobile(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def T_GET_USERINFOStart(builder): builder.StartObject(4)
def T_GET_USERINFOAddUserId(builder, userId): builder.PrependUint64Slot(0, userId, 0)
def T_GET_USERINFOAddUserName(builder, userName): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(userName), 0)
def T_GET_USERINFOAddNickName(builder, nickName): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(nickName), 0)
def T_GET_USERINFOAddMobile(builder, mobile): builder.PrependUint64Slot(3, mobile, 0)
def T_GET_USERINFOEnd(builder): return builder.EndObject()
