// automatically generated by the FlatBuffers compiler, do not modify

package offcialpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_SERVER_OFFCIAL_MESSAGE_RQ extends Table {
  public static T_SERVER_OFFCIAL_MESSAGE_RQ getRootAsT_SERVER_OFFCIAL_MESSAGE_RQ(ByteBuffer _bb) { return getRootAsT_SERVER_OFFCIAL_MESSAGE_RQ(_bb, new T_SERVER_OFFCIAL_MESSAGE_RQ()); }
  public static T_SERVER_OFFCIAL_MESSAGE_RQ getRootAsT_SERVER_OFFCIAL_MESSAGE_RQ(ByteBuffer _bb, T_SERVER_OFFCIAL_MESSAGE_RQ obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public T_SERVER_OFFCIAL_MESSAGE_RQ __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public commonpack.S_RQ_HEAD sRqHead() { return sRqHead(new commonpack.S_RQ_HEAD()); }
  public commonpack.S_RQ_HEAD sRqHead(commonpack.S_RQ_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public long messageId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long offcialId() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public commonpack.S_MSG sMsg() { return sMsg(new commonpack.S_MSG()); }
  public commonpack.S_MSG sMsg(commonpack.S_MSG obj) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public long bId() { int o = __offset(12); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long wId() { int o = __offset(14); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long cId() { int o = __offset(16); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static void startT_SERVER_OFFCIAL_MESSAGE_RQ(FlatBufferBuilder builder) { builder.startObject(7); }
  public static void addSRqHead(FlatBufferBuilder builder, int sRqHeadOffset) { builder.addStruct(0, sRqHeadOffset, 0); }
  public static void addMessageId(FlatBufferBuilder builder, long messageId) { builder.addLong(1, messageId, 0L); }
  public static void addOffcialId(FlatBufferBuilder builder, long offcialId) { builder.addLong(2, offcialId, 0L); }
  public static void addSMsg(FlatBufferBuilder builder, int sMsgOffset) { builder.addOffset(3, sMsgOffset, 0); }
  public static void addBId(FlatBufferBuilder builder, long bId) { builder.addLong(4, bId, 0L); }
  public static void addWId(FlatBufferBuilder builder, long wId) { builder.addLong(5, wId, 0L); }
  public static void addCId(FlatBufferBuilder builder, long cId) { builder.addLong(6, cId, 0L); }
  public static int endT_SERVER_OFFCIAL_MESSAGE_RQ(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_SERVER_OFFCIAL_MESSAGE_RQBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

