// automatically generated by the FlatBuffers compiler, do not modify

package userpack

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type T_CHANGE_MOBILE_RS struct {
	_tab flatbuffers.Table
}

func GetRootAsT_CHANGE_MOBILE_RS(buf []byte, offset flatbuffers.UOffsetT) *T_CHANGE_MOBILE_RS {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &T_CHANGE_MOBILE_RS{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *T_CHANGE_MOBILE_RS) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *T_CHANGE_MOBILE_RS) SRsHead(obj *S_RS_HEAD) *S_RS_HEAD {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(S_RS_HEAD)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *T_CHANGE_MOBILE_RS) OldMoblie() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *T_CHANGE_MOBILE_RS) MutateOldMoblie(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *T_CHANGE_MOBILE_RS) NewMoblie() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *T_CHANGE_MOBILE_RS) MutateNewMoblie(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func T_CHANGE_MOBILE_RSStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func T_CHANGE_MOBILE_RSAddSRsHead(builder *flatbuffers.Builder, sRsHead flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(sRsHead), 0)
}
func T_CHANGE_MOBILE_RSAddOldMoblie(builder *flatbuffers.Builder, oldMoblie uint64) {
	builder.PrependUint64Slot(1, oldMoblie, 0)
}
func T_CHANGE_MOBILE_RSAddNewMoblie(builder *flatbuffers.Builder, newMoblie uint64) {
	builder.PrependUint64Slot(2, newMoblie, 0)
}
func T_CHANGE_MOBILE_RSEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
