// automatically generated by the FlatBuffers compiler, do not modify

package userpack

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type T_REGISTER_APNS_RS struct {
	_tab flatbuffers.Table
}

func GetRootAsT_REGISTER_APNS_RS(buf []byte, offset flatbuffers.UOffsetT) *T_REGISTER_APNS_RS {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &T_REGISTER_APNS_RS{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *T_REGISTER_APNS_RS) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *T_REGISTER_APNS_RS) SRsHead(obj *S_RS_HEAD) *S_RS_HEAD {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(S_RS_HEAD)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *T_REGISTER_APNS_RS) DeviceToken() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func T_REGISTER_APNS_RSStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func T_REGISTER_APNS_RSAddSRsHead(builder *flatbuffers.Builder, sRsHead flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(sRsHead), 0)
}
func T_REGISTER_APNS_RSAddDeviceToken(builder *flatbuffers.Builder, deviceToken flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(deviceToken), 0)
}
func T_REGISTER_APNS_RSEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
