// automatically generated by the FlatBuffers compiler, do not modify

package grouppack

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type T_GROUP_RELATION_USER_INFO struct {
	_tab flatbuffers.Table
}

func GetRootAsT_GROUP_RELATION_USER_INFO(buf []byte, offset flatbuffers.UOffsetT) *T_GROUP_RELATION_USER_INFO {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &T_GROUP_RELATION_USER_INFO{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *T_GROUP_RELATION_USER_INFO) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *T_GROUP_RELATION_USER_INFO) GroupId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *T_GROUP_RELATION_USER_INFO) MutateGroupId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *T_GROUP_RELATION_USER_INFO) MessageStatus() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *T_GROUP_RELATION_USER_INFO) MutateMessageStatus(n int8) bool {
	return rcv._tab.MutateInt8Slot(6, n)
}

func (rcv *T_GROUP_RELATION_USER_INFO) SaveType() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *T_GROUP_RELATION_USER_INFO) MutateSaveType(n int8) bool {
	return rcv._tab.MutateInt8Slot(8, n)
}

func T_GROUP_RELATION_USER_INFOStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func T_GROUP_RELATION_USER_INFOAddGroupId(builder *flatbuffers.Builder, groupId uint64) {
	builder.PrependUint64Slot(0, groupId, 0)
}
func T_GROUP_RELATION_USER_INFOAddMessageStatus(builder *flatbuffers.Builder, messageStatus int8) {
	builder.PrependInt8Slot(1, messageStatus, 0)
}
func T_GROUP_RELATION_USER_INFOAddSaveType(builder *flatbuffers.Builder, saveType int8) {
	builder.PrependInt8Slot(2, saveType, 0)
}
func T_GROUP_RELATION_USER_INFOEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
