// automatically generated by the FlatBuffers compiler, do not modify

package grouppack

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type T_GROUP_MODIFY_ChANGE_RS struct {
	_tab flatbuffers.Table
}

func GetRootAsT_GROUP_MODIFY_ChANGE_RS(buf []byte, offset flatbuffers.UOffsetT) *T_GROUP_MODIFY_ChANGE_RS {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &T_GROUP_MODIFY_ChANGE_RS{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *T_GROUP_MODIFY_ChANGE_RS) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *T_GROUP_MODIFY_ChANGE_RS) SRsHead(obj *S_RS_HEAD) *S_RS_HEAD {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(S_RS_HEAD)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *T_GROUP_MODIFY_ChANGE_RS) GroupInfo(obj *T_GROUP_BASE_INFO) *T_GROUP_BASE_INFO {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(T_GROUP_BASE_INFO)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *T_GROUP_MODIFY_ChANGE_RS) OfflineGroupMsg(obj *T_OFFLINE_GROUP_MSG) *T_OFFLINE_GROUP_MSG {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(T_OFFLINE_GROUP_MSG)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func T_GROUP_MODIFY_ChANGE_RSStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func T_GROUP_MODIFY_ChANGE_RSAddSRsHead(builder *flatbuffers.Builder, sRsHead flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(sRsHead), 0)
}
func T_GROUP_MODIFY_ChANGE_RSAddGroupInfo(builder *flatbuffers.Builder, groupInfo flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(groupInfo), 0)
}
func T_GROUP_MODIFY_ChANGE_RSAddOfflineGroupMsg(builder *flatbuffers.Builder, offlineGroupMsg flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(offlineGroupMsg), 0)
}
func T_GROUP_MODIFY_ChANGE_RSEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
