// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var commonpack = commonpack || {};

/**
 * @const
 * @namespace
 */
var friendpack = friendpack || {};

/**
 * @constructor
 */
friendpack.T_FRIEND_CLIENT_ADD_RS = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {friendpack.T_FRIEND_CLIENT_ADD_RS}
 */
friendpack.T_FRIEND_CLIENT_ADD_RS.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {friendpack.T_FRIEND_CLIENT_ADD_RS=} obj
 * @returns {friendpack.T_FRIEND_CLIENT_ADD_RS}
 */
friendpack.T_FRIEND_CLIENT_ADD_RS.getRootAsT_FRIEND_CLIENT_ADD_RS = function(bb, obj) {
  return (obj || new friendpack.T_FRIEND_CLIENT_ADD_RS).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {commonpack.S_RS_HEAD=} obj
 * @returns {commonpack.S_RS_HEAD}
 */
friendpack.T_FRIEND_CLIENT_ADD_RS.prototype.sRsHead = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new commonpack.S_RS_HEAD).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
friendpack.T_FRIEND_CLIENT_ADD_RS.prototype.peerUserId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
friendpack.T_FRIEND_CLIENT_ADD_RS.prototype.token = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
friendpack.T_FRIEND_CLIENT_ADD_RS.prototype.opMsg = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
friendpack.T_FRIEND_CLIENT_ADD_RS.startT_FRIEND_CLIENT_ADD_RS = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sRsHeadOffset
 */
friendpack.T_FRIEND_CLIENT_ADD_RS.addSRsHead = function(builder, sRsHeadOffset) {
  builder.addFieldStruct(0, sRsHeadOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} peerUserId
 */
friendpack.T_FRIEND_CLIENT_ADD_RS.addPeerUserId = function(builder, peerUserId) {
  builder.addFieldInt64(1, peerUserId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} token
 */
friendpack.T_FRIEND_CLIENT_ADD_RS.addToken = function(builder, token) {
  builder.addFieldInt64(2, token, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} opMsgOffset
 */
friendpack.T_FRIEND_CLIENT_ADD_RS.addOpMsg = function(builder, opMsgOffset) {
  builder.addFieldOffset(3, opMsgOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
friendpack.T_FRIEND_CLIENT_ADD_RS.endT_FRIEND_CLIENT_ADD_RS = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
friendpack.T_FRIEND_CLIENT_ADD_RS.finishT_FRIEND_CLIENT_ADD_RSBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.commonpack = commonpack;
this.friendpack = friendpack;
