// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var commonpack = commonpack || {};

/**
 * @const
 * @namespace
 */
var friendpack = friendpack || {};

/**
 * @constructor
 */
friendpack.T_FRIEND_REMARK_RQ = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {friendpack.T_FRIEND_REMARK_RQ}
 */
friendpack.T_FRIEND_REMARK_RQ.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {friendpack.T_FRIEND_REMARK_RQ=} obj
 * @returns {friendpack.T_FRIEND_REMARK_RQ}
 */
friendpack.T_FRIEND_REMARK_RQ.getRootAsT_FRIEND_REMARK_RQ = function(bb, obj) {
  return (obj || new friendpack.T_FRIEND_REMARK_RQ).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {commonpack.S_RQ_HEAD=} obj
 * @returns {commonpack.S_RQ_HEAD}
 */
friendpack.T_FRIEND_REMARK_RQ.prototype.sRqHead = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new commonpack.S_RQ_HEAD).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
friendpack.T_FRIEND_REMARK_RQ.prototype.peerUserId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
friendpack.T_FRIEND_REMARK_RQ.prototype.peerRemarkName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
friendpack.T_FRIEND_REMARK_RQ.startT_FRIEND_REMARK_RQ = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sRqHeadOffset
 */
friendpack.T_FRIEND_REMARK_RQ.addSRqHead = function(builder, sRqHeadOffset) {
  builder.addFieldStruct(0, sRqHeadOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} peerUserId
 */
friendpack.T_FRIEND_REMARK_RQ.addPeerUserId = function(builder, peerUserId) {
  builder.addFieldInt64(1, peerUserId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} peerRemarkNameOffset
 */
friendpack.T_FRIEND_REMARK_RQ.addPeerRemarkName = function(builder, peerRemarkNameOffset) {
  builder.addFieldOffset(2, peerRemarkNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
friendpack.T_FRIEND_REMARK_RQ.endT_FRIEND_REMARK_RQ = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
friendpack.T_FRIEND_REMARK_RQ.finishT_FRIEND_REMARK_RQBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.commonpack = commonpack;
this.friendpack = friendpack;
