// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var commonpack = commonpack || {};

/**
 * @const
 * @namespace
 */
var ecpack = ecpack || {};

/**
 * @constructor
 */
ecpack.T_EC_GETRECENTORDERS_RS = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ecpack.T_EC_GETRECENTORDERS_RS}
 */
ecpack.T_EC_GETRECENTORDERS_RS.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ecpack.T_EC_GETRECENTORDERS_RS=} obj
 * @returns {ecpack.T_EC_GETRECENTORDERS_RS}
 */
ecpack.T_EC_GETRECENTORDERS_RS.getRootAsT_EC_GETRECENTORDERS_RS = function(bb, obj) {
  return (obj || new ecpack.T_EC_GETRECENTORDERS_RS).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {commonpack.S_RS_HEAD=} obj
 * @returns {commonpack.S_RS_HEAD}
 */
ecpack.T_EC_GETRECENTORDERS_RS.prototype.sRsHead = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new commonpack.S_RS_HEAD).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {number}
 */
ecpack.T_EC_GETRECENTORDERS_RS.prototype.code = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {ecpack.T_ORDER_INFO=} obj
 * @returns {ecpack.T_ORDER_INFO}
 */
ecpack.T_EC_GETRECENTORDERS_RS.prototype.orderList = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new ecpack.T_ORDER_INFO).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
ecpack.T_EC_GETRECENTORDERS_RS.prototype.orderListLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ecpack.T_EC_GETRECENTORDERS_RS.startT_EC_GETRECENTORDERS_RS = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sRsHeadOffset
 */
ecpack.T_EC_GETRECENTORDERS_RS.addSRsHead = function(builder, sRsHeadOffset) {
  builder.addFieldStruct(0, sRsHeadOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} code
 */
ecpack.T_EC_GETRECENTORDERS_RS.addCode = function(builder, code) {
  builder.addFieldInt32(1, code, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} orderListOffset
 */
ecpack.T_EC_GETRECENTORDERS_RS.addOrderList = function(builder, orderListOffset) {
  builder.addFieldOffset(2, orderListOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
ecpack.T_EC_GETRECENTORDERS_RS.createOrderListVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
ecpack.T_EC_GETRECENTORDERS_RS.startOrderListVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ecpack.T_EC_GETRECENTORDERS_RS.endT_EC_GETRECENTORDERS_RS = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
ecpack.T_EC_GETRECENTORDERS_RS.finishT_EC_GETRECENTORDERS_RSBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.commonpack = commonpack;
this.ecpack = ecpack;
