// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var commonpack = commonpack || {};

/**
 * @const
 * @namespace
 */
var syspack = syspack || {};

/**
 * @constructor
 */
syspack.T_SMS_VALID_RS = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {syspack.T_SMS_VALID_RS}
 */
syspack.T_SMS_VALID_RS.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {syspack.T_SMS_VALID_RS=} obj
 * @returns {syspack.T_SMS_VALID_RS}
 */
syspack.T_SMS_VALID_RS.getRootAsT_SMS_VALID_RS = function(bb, obj) {
  return (obj || new syspack.T_SMS_VALID_RS).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {commonpack.S_RS_HEAD=} obj
 * @returns {commonpack.S_RS_HEAD}
 */
syspack.T_SMS_VALID_RS.prototype.sRsHead = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new commonpack.S_RS_HEAD).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {number}
 */
syspack.T_SMS_VALID_RS.prototype.verifyCode = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
syspack.T_SMS_VALID_RS.startT_SMS_VALID_RS = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sRsHeadOffset
 */
syspack.T_SMS_VALID_RS.addSRsHead = function(builder, sRsHeadOffset) {
  builder.addFieldStruct(0, sRsHeadOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} verifyCode
 */
syspack.T_SMS_VALID_RS.addVerifyCode = function(builder, verifyCode) {
  builder.addFieldInt32(1, verifyCode, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
syspack.T_SMS_VALID_RS.endT_SMS_VALID_RS = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
syspack.T_SMS_VALID_RS.finishT_SMS_VALID_RSBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.commonpack = commonpack;
this.syspack = syspack;
