// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var commonpack = commonpack || {};

/**
 * @const
 * @namespace
 */
var syspack = syspack || {};

/**
 * @constructor
 */
syspack.T_SERVER_DISCON_ID = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {syspack.T_SERVER_DISCON_ID}
 */
syspack.T_SERVER_DISCON_ID.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {syspack.T_SERVER_DISCON_ID=} obj
 * @returns {syspack.T_SERVER_DISCON_ID}
 */
syspack.T_SERVER_DISCON_ID.getRootAsT_SERVER_DISCON_ID = function(bb, obj) {
  return (obj || new syspack.T_SERVER_DISCON_ID).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
syspack.T_SERVER_DISCON_ID.prototype.result = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
syspack.T_SERVER_DISCON_ID.startT_SERVER_DISCON_ID = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} result
 */
syspack.T_SERVER_DISCON_ID.addResult = function(builder, result) {
  builder.addFieldInt32(0, result, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
syspack.T_SERVER_DISCON_ID.endT_SERVER_DISCON_ID = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
syspack.T_SERVER_DISCON_ID.finishT_SERVER_DISCON_IDBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.commonpack = commonpack;
this.syspack = syspack;
