# automatically generated by the FlatBuffers compiler, do not modify

# namespace: friendpack

import flatbuffers

class T_CLINET_FRIEND_BLACKLIST_RS(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsT_CLINET_FRIEND_BLACKLIST_RS(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = T_CLINET_FRIEND_BLACKLIST_RS()
        x.Init(buf, n + offset)
        return x

    # T_CLINET_FRIEND_BLACKLIST_RS
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # T_CLINET_FRIEND_BLACKLIST_RS
    def SRsHead(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .S_RS_HEAD import S_RS_HEAD
            obj = S_RS_HEAD()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # T_CLINET_FRIEND_BLACKLIST_RS
    def PeerUserId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # T_CLINET_FRIEND_BLACKLIST_RS
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # T_CLINET_FRIEND_BLACKLIST_RS
    def Token(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def T_CLINET_FRIEND_BLACKLIST_RSStart(builder): builder.StartObject(4)
def T_CLINET_FRIEND_BLACKLIST_RSAddSRsHead(builder, sRsHead): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sRsHead), 0)
def T_CLINET_FRIEND_BLACKLIST_RSAddPeerUserId(builder, peerUserId): builder.PrependUint64Slot(1, peerUserId, 0)
def T_CLINET_FRIEND_BLACKLIST_RSAddType(builder, type): builder.PrependInt32Slot(2, type, 0)
def T_CLINET_FRIEND_BLACKLIST_RSAddToken(builder, token): builder.PrependUint64Slot(3, token, 0)
def T_CLINET_FRIEND_BLACKLIST_RSEnd(builder): return builder.EndObject()
