# automatically generated by the FlatBuffers compiler, do not modify

# namespace: friendpack

import flatbuffers

class T_FRIEND_SERVER_DEL_RS(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsT_FRIEND_SERVER_DEL_RS(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = T_FRIEND_SERVER_DEL_RS()
        x.Init(buf, n + offset)
        return x

    # T_FRIEND_SERVER_DEL_RS
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # T_FRIEND_SERVER_DEL_RS
    def SRsHead(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .S_RS_HEAD import S_RS_HEAD
            obj = S_RS_HEAD()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def T_FRIEND_SERVER_DEL_RSStart(builder): builder.StartObject(1)
def T_FRIEND_SERVER_DEL_RSAddSRsHead(builder, sRsHead): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sRsHead), 0)
def T_FRIEND_SERVER_DEL_RSEnd(builder): return builder.EndObject()
