// automatically generated by the FlatBuffers compiler, do not modify

package ecpack

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type T_EC_SETPROMPTS_RQ struct {
	_tab flatbuffers.Table
}

func GetRootAsT_EC_SETPROMPTS_RQ(buf []byte, offset flatbuffers.UOffsetT) *T_EC_SETPROMPTS_RQ {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &T_EC_SETPROMPTS_RQ{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *T_EC_SETPROMPTS_RQ) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *T_EC_SETPROMPTS_RQ) SRqHead(obj *S_RQ_HEAD) *S_RQ_HEAD {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(S_RQ_HEAD)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *T_EC_SETPROMPTS_RQ) Promptsmsglist(obj *T_PROMPTMSG_INFO, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *T_EC_SETPROMPTS_RQ) PromptsmsglistLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func T_EC_SETPROMPTS_RQStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func T_EC_SETPROMPTS_RQAddSRqHead(builder *flatbuffers.Builder, sRqHead flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(sRqHead), 0)
}
func T_EC_SETPROMPTS_RQAddPromptsmsglist(builder *flatbuffers.Builder, promptsmsglist flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(promptsmsglist), 0)
}
func T_EC_SETPROMPTS_RQStartPromptsmsglistVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func T_EC_SETPROMPTS_RQEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
