// automatically generated by the FlatBuffers compiler, do not modify

package ecpack

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type T_EC_SETBUSINESS_RQ struct {
	_tab flatbuffers.Table
}

func GetRootAsT_EC_SETBUSINESS_RQ(buf []byte, offset flatbuffers.UOffsetT) *T_EC_SETBUSINESS_RQ {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &T_EC_SETBUSINESS_RQ{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *T_EC_SETBUSINESS_RQ) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *T_EC_SETBUSINESS_RQ) SRqHead(obj *S_RQ_HEAD) *S_RQ_HEAD {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(S_RQ_HEAD)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *T_EC_SETBUSINESS_RQ) SellerId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *T_EC_SETBUSINESS_RQ) MutateSellerId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *T_EC_SETBUSINESS_RQ) SellerType() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *T_EC_SETBUSINESS_RQ) MutateSellerType(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *T_EC_SETBUSINESS_RQ) SellerAvatar() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *T_EC_SETBUSINESS_RQ) SellerName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *T_EC_SETBUSINESS_RQ) SellerUrl() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func T_EC_SETBUSINESS_RQStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func T_EC_SETBUSINESS_RQAddSRqHead(builder *flatbuffers.Builder, sRqHead flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(sRqHead), 0)
}
func T_EC_SETBUSINESS_RQAddSellerId(builder *flatbuffers.Builder, sellerId uint64) {
	builder.PrependUint64Slot(1, sellerId, 0)
}
func T_EC_SETBUSINESS_RQAddSellerType(builder *flatbuffers.Builder, sellerType int32) {
	builder.PrependInt32Slot(2, sellerType, 0)
}
func T_EC_SETBUSINESS_RQAddSellerAvatar(builder *flatbuffers.Builder, sellerAvatar flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(sellerAvatar), 0)
}
func T_EC_SETBUSINESS_RQAddSellerName(builder *flatbuffers.Builder, sellerName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(sellerName), 0)
}
func T_EC_SETBUSINESS_RQAddSellerUrl(builder *flatbuffers.Builder, sellerUrl flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(sellerUrl), 0)
}
func T_EC_SETBUSINESS_RQEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
