// automatically generated by the FlatBuffers compiler, do not modify

package ecpack

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type T_EC_GET_OFFLINE_MESSAGE_RS struct {
	_tab flatbuffers.Table
}

func GetRootAsT_EC_GET_OFFLINE_MESSAGE_RS(buf []byte, offset flatbuffers.UOffsetT) *T_EC_GET_OFFLINE_MESSAGE_RS {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &T_EC_GET_OFFLINE_MESSAGE_RS{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *T_EC_GET_OFFLINE_MESSAGE_RS) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *T_EC_GET_OFFLINE_MESSAGE_RS) SRsHead(obj *S_RS_HEAD) *S_RS_HEAD {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(S_RS_HEAD)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *T_EC_GET_OFFLINE_MESSAGE_RS) BId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *T_EC_GET_OFFLINE_MESSAGE_RS) MutateBId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *T_EC_GET_OFFLINE_MESSAGE_RS) Offset() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *T_EC_GET_OFFLINE_MESSAGE_RS) MutateOffset(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *T_EC_GET_OFFLINE_MESSAGE_RS) MsgList(obj *T_ECMSG_INFO, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *T_EC_GET_OFFLINE_MESSAGE_RS) MsgListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func T_EC_GET_OFFLINE_MESSAGE_RSStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func T_EC_GET_OFFLINE_MESSAGE_RSAddSRsHead(builder *flatbuffers.Builder, sRsHead flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(sRsHead), 0)
}
func T_EC_GET_OFFLINE_MESSAGE_RSAddBId(builder *flatbuffers.Builder, bId uint64) {
	builder.PrependUint64Slot(1, bId, 0)
}
func T_EC_GET_OFFLINE_MESSAGE_RSAddOffset(builder *flatbuffers.Builder, offset int32) {
	builder.PrependInt32Slot(2, offset, 0)
}
func T_EC_GET_OFFLINE_MESSAGE_RSAddMsgList(builder *flatbuffers.Builder, msgList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(msgList), 0)
}
func T_EC_GET_OFFLINE_MESSAGE_RSStartMsgListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func T_EC_GET_OFFLINE_MESSAGE_RSEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
