// automatically generated by the FlatBuffers compiler, do not modify

package ecpack

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type T_EC_GETRECENTUSERS_RS struct {
	_tab flatbuffers.Table
}

func GetRootAsT_EC_GETRECENTUSERS_RS(buf []byte, offset flatbuffers.UOffsetT) *T_EC_GETRECENTUSERS_RS {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &T_EC_GETRECENTUSERS_RS{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *T_EC_GETRECENTUSERS_RS) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *T_EC_GETRECENTUSERS_RS) SRsHead(obj *S_RS_HEAD) *S_RS_HEAD {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(S_RS_HEAD)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *T_EC_GETRECENTUSERS_RS) BId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *T_EC_GETRECENTUSERS_RS) MutateBId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *T_EC_GETRECENTUSERS_RS) CIdList(j int) uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *T_EC_GETRECENTUSERS_RS) CIdListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func T_EC_GETRECENTUSERS_RSStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func T_EC_GETRECENTUSERS_RSAddSRsHead(builder *flatbuffers.Builder, sRsHead flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(sRsHead), 0)
}
func T_EC_GETRECENTUSERS_RSAddBId(builder *flatbuffers.Builder, bId uint64) {
	builder.PrependUint64Slot(1, bId, 0)
}
func T_EC_GETRECENTUSERS_RSAddCIdList(builder *flatbuffers.Builder, cIdList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(cIdList), 0)
}
func T_EC_GETRECENTUSERS_RSStartCIdListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func T_EC_GETRECENTUSERS_RSEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
