// automatically generated by the FlatBuffers compiler, do not modify

package momentspack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_MOMENTS_ARTICLE_ADD_NOTIFY extends Table {
  public static T_MOMENTS_ARTICLE_ADD_NOTIFY getRootAsT_MOMENTS_ARTICLE_ADD_NOTIFY(ByteBuffer _bb) { return getRootAsT_MOMENTS_ARTICLE_ADD_NOTIFY(_bb, new T_MOMENTS_ARTICLE_ADD_NOTIFY()); }
  public static T_MOMENTS_ARTICLE_ADD_NOTIFY getRootAsT_MOMENTS_ARTICLE_ADD_NOTIFY(ByteBuffer _bb, T_MOMENTS_ARTICLE_ADD_NOTIFY obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public T_MOMENTS_ARTICLE_ADD_NOTIFY __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long momentsChangeAt() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createT_MOMENTS_ARTICLE_ADD_NOTIFY(FlatBufferBuilder builder,
      long moments_change_at) {
    builder.startObject(1);
    T_MOMENTS_ARTICLE_ADD_NOTIFY.addMomentsChangeAt(builder, moments_change_at);
    return T_MOMENTS_ARTICLE_ADD_NOTIFY.endT_MOMENTS_ARTICLE_ADD_NOTIFY(builder);
  }

  public static void startT_MOMENTS_ARTICLE_ADD_NOTIFY(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addMomentsChangeAt(FlatBufferBuilder builder, long momentsChangeAt) { builder.addLong(0, momentsChangeAt, 0L); }
  public static int endT_MOMENTS_ARTICLE_ADD_NOTIFY(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_MOMENTS_ARTICLE_ADD_NOTIFYBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

