// automatically generated by the FlatBuffers compiler, do not modify

package momentspack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_MOMENTS_COMMENT_DELETE_RQ extends Table {
  public static T_MOMENTS_COMMENT_DELETE_RQ getRootAsT_MOMENTS_COMMENT_DELETE_RQ(ByteBuffer _bb) { return getRootAsT_MOMENTS_COMMENT_DELETE_RQ(_bb, new T_MOMENTS_COMMENT_DELETE_RQ()); }
  public static T_MOMENTS_COMMENT_DELETE_RQ getRootAsT_MOMENTS_COMMENT_DELETE_RQ(ByteBuffer _bb, T_MOMENTS_COMMENT_DELETE_RQ obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public T_MOMENTS_COMMENT_DELETE_RQ __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public commonpack.S_RQ_HEAD sRqHead() { return sRqHead(new commonpack.S_RQ_HEAD()); }
  public commonpack.S_RQ_HEAD sRqHead(commonpack.S_RQ_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public long articleId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long articleUserId() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long userId() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long commentId() { int o = __offset(12); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static void startT_MOMENTS_COMMENT_DELETE_RQ(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addSRqHead(FlatBufferBuilder builder, int sRqHeadOffset) { builder.addStruct(0, sRqHeadOffset, 0); }
  public static void addArticleId(FlatBufferBuilder builder, long articleId) { builder.addLong(1, articleId, 0L); }
  public static void addArticleUserId(FlatBufferBuilder builder, long articleUserId) { builder.addLong(2, articleUserId, 0L); }
  public static void addUserId(FlatBufferBuilder builder, long userId) { builder.addLong(3, userId, 0L); }
  public static void addCommentId(FlatBufferBuilder builder, long commentId) { builder.addLong(4, commentId, 0L); }
  public static int endT_MOMENTS_COMMENT_DELETE_RQ(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_MOMENTS_COMMENT_DELETE_RQBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

