// automatically generated by the FlatBuffers compiler, do not modify

package momentspack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_MOMENTS_SETTING_MODIFY_NOTIFY extends Table {
  public static T_MOMENTS_SETTING_MODIFY_NOTIFY getRootAsT_MOMENTS_SETTING_MODIFY_NOTIFY(ByteBuffer _bb) { return getRootAsT_MOMENTS_SETTING_MODIFY_NOTIFY(_bb, new T_MOMENTS_SETTING_MODIFY_NOTIFY()); }
  public static T_MOMENTS_SETTING_MODIFY_NOTIFY getRootAsT_MOMENTS_SETTING_MODIFY_NOTIFY(ByteBuffer _bb, T_MOMENTS_SETTING_MODIFY_NOTIFY obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public T_MOMENTS_SETTING_MODIFY_NOTIFY __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long userId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public momentspack.T_MOMENTS_SETTING_DTO setting() { return setting(new momentspack.T_MOMENTS_SETTING_DTO()); }
  public momentspack.T_MOMENTS_SETTING_DTO setting(momentspack.T_MOMENTS_SETTING_DTO obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createT_MOMENTS_SETTING_MODIFY_NOTIFY(FlatBufferBuilder builder,
      long user_id,
      int settingOffset) {
    builder.startObject(2);
    T_MOMENTS_SETTING_MODIFY_NOTIFY.addUserId(builder, user_id);
    T_MOMENTS_SETTING_MODIFY_NOTIFY.addSetting(builder, settingOffset);
    return T_MOMENTS_SETTING_MODIFY_NOTIFY.endT_MOMENTS_SETTING_MODIFY_NOTIFY(builder);
  }

  public static void startT_MOMENTS_SETTING_MODIFY_NOTIFY(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addUserId(FlatBufferBuilder builder, long userId) { builder.addLong(0, userId, 0L); }
  public static void addSetting(FlatBufferBuilder builder, int settingOffset) { builder.addOffset(1, settingOffset, 0); }
  public static int endT_MOMENTS_SETTING_MODIFY_NOTIFY(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_MOMENTS_SETTING_MODIFY_NOTIFYBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

