// automatically generated by the FlatBuffers compiler, do not modify

package momentspack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_MOMENTS_ARTICLE_DELETE_NOTIFY extends Table {
  public static T_MOMENTS_ARTICLE_DELETE_NOTIFY getRootAsT_MOMENTS_ARTICLE_DELETE_NOTIFY(ByteBuffer _bb) { return getRootAsT_MOMENTS_ARTICLE_DELETE_NOTIFY(_bb, new T_MOMENTS_ARTICLE_DELETE_NOTIFY()); }
  public static T_MOMENTS_ARTICLE_DELETE_NOTIFY getRootAsT_MOMENTS_ARTICLE_DELETE_NOTIFY(ByteBuffer _bb, T_MOMENTS_ARTICLE_DELETE_NOTIFY obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public T_MOMENTS_ARTICLE_DELETE_NOTIFY __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long articleId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long articleUserId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createT_MOMENTS_ARTICLE_DELETE_NOTIFY(FlatBufferBuilder builder,
      long article_id,
      long article_user_id) {
    builder.startObject(2);
    T_MOMENTS_ARTICLE_DELETE_NOTIFY.addArticleUserId(builder, article_user_id);
    T_MOMENTS_ARTICLE_DELETE_NOTIFY.addArticleId(builder, article_id);
    return T_MOMENTS_ARTICLE_DELETE_NOTIFY.endT_MOMENTS_ARTICLE_DELETE_NOTIFY(builder);
  }

  public static void startT_MOMENTS_ARTICLE_DELETE_NOTIFY(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addArticleId(FlatBufferBuilder builder, long articleId) { builder.addLong(0, articleId, 0L); }
  public static void addArticleUserId(FlatBufferBuilder builder, long articleUserId) { builder.addLong(1, articleUserId, 0L); }
  public static int endT_MOMENTS_ARTICLE_DELETE_NOTIFY(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_MOMENTS_ARTICLE_DELETE_NOTIFYBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

