// automatically generated by the FlatBuffers compiler, do not modify

package ecpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_PROMPTMSG_INFO extends Table {
  public static T_PROMPTMSG_INFO getRootAsT_PROMPTMSG_INFO(ByteBuffer _bb) { return getRootAsT_PROMPTMSG_INFO(_bb, new T_PROMPTMSG_INFO()); }
  public static T_PROMPTMSG_INFO getRootAsT_PROMPTMSG_INFO(ByteBuffer _bb, T_PROMPTMSG_INFO obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public T_PROMPTMSG_INFO __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long bId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public int promptsType() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String promptsMsg() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer promptsMsgAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }

  public static int createT_PROMPTMSG_INFO(FlatBufferBuilder builder,
      long b_id,
      int prompts_type,
      int prompts_msgOffset) {
    builder.startObject(3);
    T_PROMPTMSG_INFO.addBId(builder, b_id);
    T_PROMPTMSG_INFO.addPromptsMsg(builder, prompts_msgOffset);
    T_PROMPTMSG_INFO.addPromptsType(builder, prompts_type);
    return T_PROMPTMSG_INFO.endT_PROMPTMSG_INFO(builder);
  }

  public static void startT_PROMPTMSG_INFO(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addBId(FlatBufferBuilder builder, long bId) { builder.addLong(0, bId, 0L); }
  public static void addPromptsType(FlatBufferBuilder builder, int promptsType) { builder.addInt(1, promptsType, 0); }
  public static void addPromptsMsg(FlatBufferBuilder builder, int promptsMsgOffset) { builder.addOffset(2, promptsMsgOffset, 0); }
  public static int endT_PROMPTMSG_INFO(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_PROMPTMSG_INFOBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

